package com.zytx.common.entity;

public class MMember {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.area_code
     *
     * @mbggenerated
     */
    private Integer areaCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.m_name
     *
     * @mbggenerated
     */
    private String mName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.m_nick_name
     *
     * @mbggenerated
     */
    private String mNickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.sms_code
     *
     * @mbggenerated
     */
    private String smsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.sms_code_time
     *
     * @mbggenerated
     */
    private String smsCodeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.m_pwd
     *
     * @mbggenerated
     */
    private String mPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.m_security_pwd
     *
     * @mbggenerated
     */
    private String mSecurityPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.reg_time
     *
     * @mbggenerated
     */
    private String regTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.last_login_ip
     *
     * @mbggenerated
     */
    private String lastLoginIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.last_login_time
     *
     * @mbggenerated
     */
    private String lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.last_mod_pwd_time
     *
     * @mbggenerated
     */
    private String lastModPwdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.auth_grade
     *
     * @mbggenerated
     */
    private Integer authGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.m_status
     *
     * @mbggenerated
     */
    private Integer mStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.api_status
     *
     * @mbggenerated
     */
    private Integer apiStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.api_limit
     *
     * @mbggenerated
     */
    private Byte apiLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.introduce_m_id
     *
     * @mbggenerated
     */
    private String introduceMId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.google_auth_key
     *
     * @mbggenerated
     */
    private String googleAuthKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.trade_commission
     *
     * @mbggenerated
     */
    private Double tradeCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.inter_standard
     *
     * @mbggenerated
     */
    private String interStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.invite_code
     *
     * @mbggenerated
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_member.last_login_device
     *
     * @mbggenerated
     */
    private String lastLoginDevice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.id
     *
     * @return the value of m_member.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.id
     *
     * @param id the value for m_member.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.area_code
     *
     * @return the value of m_member.area_code
     *
     * @mbggenerated
     */
    public Integer getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.area_code
     *
     * @param areaCode the value for m_member.area_code
     *
     * @mbggenerated
     */
    public void setAreaCode(Integer areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.m_name
     *
     * @return the value of m_member.m_name
     *
     * @mbggenerated
     */
    public String getmName() {
        return mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.m_name
     *
     * @param mName the value for m_member.m_name
     *
     * @mbggenerated
     */
    public void setmName(String mName) {
        this.mName = mName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.m_nick_name
     *
     * @return the value of m_member.m_nick_name
     *
     * @mbggenerated
     */
    public String getmNickName() {
        return mNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.m_nick_name
     *
     * @param mNickName the value for m_member.m_nick_name
     *
     * @mbggenerated
     */
    public void setmNickName(String mNickName) {
        this.mNickName = mNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.sms_code
     *
     * @return the value of m_member.sms_code
     *
     * @mbggenerated
     */
    public String getSmsCode() {
        return smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.sms_code
     *
     * @param smsCode the value for m_member.sms_code
     *
     * @mbggenerated
     */
    public void setSmsCode(String smsCode) {
        this.smsCode = smsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.sms_code_time
     *
     * @return the value of m_member.sms_code_time
     *
     * @mbggenerated
     */
    public String getSmsCodeTime() {
        return smsCodeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.sms_code_time
     *
     * @param smsCodeTime the value for m_member.sms_code_time
     *
     * @mbggenerated
     */
    public void setSmsCodeTime(String smsCodeTime) {
        this.smsCodeTime = smsCodeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.m_pwd
     *
     * @return the value of m_member.m_pwd
     *
     * @mbggenerated
     */
    public String getmPwd() {
        return mPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.m_pwd
     *
     * @param mPwd the value for m_member.m_pwd
     *
     * @mbggenerated
     */
    public void setmPwd(String mPwd) {
        this.mPwd = mPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.m_security_pwd
     *
     * @return the value of m_member.m_security_pwd
     *
     * @mbggenerated
     */
    public String getmSecurityPwd() {
        return mSecurityPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.m_security_pwd
     *
     * @param mSecurityPwd the value for m_member.m_security_pwd
     *
     * @mbggenerated
     */
    public void setmSecurityPwd(String mSecurityPwd) {
        this.mSecurityPwd = mSecurityPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.reg_time
     *
     * @return the value of m_member.reg_time
     *
     * @mbggenerated
     */
    public String getRegTime() {
        return regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.reg_time
     *
     * @param regTime the value for m_member.reg_time
     *
     * @mbggenerated
     */
    public void setRegTime(String regTime) {
        this.regTime = regTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.last_login_ip
     *
     * @return the value of m_member.last_login_ip
     *
     * @mbggenerated
     */
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.last_login_ip
     *
     * @param lastLoginIp the value for m_member.last_login_ip
     *
     * @mbggenerated
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.last_login_time
     *
     * @return the value of m_member.last_login_time
     *
     * @mbggenerated
     */
    public String getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.last_login_time
     *
     * @param lastLoginTime the value for m_member.last_login_time
     *
     * @mbggenerated
     */
    public void setLastLoginTime(String lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.last_mod_pwd_time
     *
     * @return the value of m_member.last_mod_pwd_time
     *
     * @mbggenerated
     */
    public String getLastModPwdTime() {
        return lastModPwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.last_mod_pwd_time
     *
     * @param lastModPwdTime the value for m_member.last_mod_pwd_time
     *
     * @mbggenerated
     */
    public void setLastModPwdTime(String lastModPwdTime) {
        this.lastModPwdTime = lastModPwdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.auth_grade
     *
     * @return the value of m_member.auth_grade
     *
     * @mbggenerated
     */
    public Integer getAuthGrade() {
        return authGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.auth_grade
     *
     * @param authGrade the value for m_member.auth_grade
     *
     * @mbggenerated
     */
    public void setAuthGrade(Integer authGrade) {
        this.authGrade = authGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.m_status
     *
     * @return the value of m_member.m_status
     *
     * @mbggenerated
     */
    public Integer getmStatus() {
        return mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.m_status
     *
     * @param mStatus the value for m_member.m_status
     *
     * @mbggenerated
     */
    public void setmStatus(Integer mStatus) {
        this.mStatus = mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.api_status
     *
     * @return the value of m_member.api_status
     *
     * @mbggenerated
     */
    public Integer getApiStatus() {
        return apiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.api_status
     *
     * @param apiStatus the value for m_member.api_status
     *
     * @mbggenerated
     */
    public void setApiStatus(Integer apiStatus) {
        this.apiStatus = apiStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.api_limit
     *
     * @return the value of m_member.api_limit
     *
     * @mbggenerated
     */
    public Byte getApiLimit() {
        return apiLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.api_limit
     *
     * @param apiLimit the value for m_member.api_limit
     *
     * @mbggenerated
     */
    public void setApiLimit(Byte apiLimit) {
        this.apiLimit = apiLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.introduce_m_id
     *
     * @return the value of m_member.introduce_m_id
     *
     * @mbggenerated
     */
    public String getIntroduceMId() {
        return introduceMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.introduce_m_id
     *
     * @param introduceMId the value for m_member.introduce_m_id
     *
     * @mbggenerated
     */
    public void setIntroduceMId(String introduceMId) {
        this.introduceMId = introduceMId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.google_auth_key
     *
     * @return the value of m_member.google_auth_key
     *
     * @mbggenerated
     */
    public String getGoogleAuthKey() {
        return googleAuthKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.google_auth_key
     *
     * @param googleAuthKey the value for m_member.google_auth_key
     *
     * @mbggenerated
     */
    public void setGoogleAuthKey(String googleAuthKey) {
        this.googleAuthKey = googleAuthKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.trade_commission
     *
     * @return the value of m_member.trade_commission
     *
     * @mbggenerated
     */
    public Double getTradeCommission() {
        return tradeCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.trade_commission
     *
     * @param tradeCommission the value for m_member.trade_commission
     *
     * @mbggenerated
     */
    public void setTradeCommission(Double tradeCommission) {
        this.tradeCommission = tradeCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.phone
     *
     * @return the value of m_member.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.phone
     *
     * @param phone the value for m_member.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.inter_standard
     *
     * @return the value of m_member.inter_standard
     *
     * @mbggenerated
     */
    public String getInterStandard() {
        return interStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.inter_standard
     *
     * @param interStandard the value for m_member.inter_standard
     *
     * @mbggenerated
     */
    public void setInterStandard(String interStandard) {
        this.interStandard = interStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.invite_code
     *
     * @return the value of m_member.invite_code
     *
     * @mbggenerated
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.invite_code
     *
     * @param inviteCode the value for m_member.invite_code
     *
     * @mbggenerated
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_member.last_login_device
     *
     * @return the value of m_member.last_login_device
     *
     * @mbggenerated
     */
    public String getLastLoginDevice() {
        return lastLoginDevice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_member.last_login_device
     *
     * @param lastLoginDevice the value for m_member.last_login_device
     *
     * @mbggenerated
     */
    public void setLastLoginDevice(String lastLoginDevice) {
        this.lastLoginDevice = lastLoginDevice;
    }
}