package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.contract.service.Page;

public class CCashUsdtLogs extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6403780101791275513L;

	/**  */
    private Integer id;

    /**  */
    private Integer cid;

    /** 提供者地址 */
    private String fromaddr;

    /** 提币数量 */
    private BigDecimal money;

    /** 手续费 */
    private BigDecimal tax;

    /** 实际到账 */
    private BigDecimal realmoney;

    /** 接收者 */
    private String toaddr;

    /** 1待审核 2已通过 3已驳回 */
    private Integer status;

    /** 交易单号 */
    private String hashcode;

    /**  */
    private Date createtime;

    /** 审核时间 */
    private Date checktime;

    /** 审核人 */
    private Integer checkid;

    /** 对账时间 */
    private Date dztime;

    /** -1未对账  0正常交易，1需要重审 */
    private Integer dzstatus;
    
    private String checker;
    
    private String login;
    
    private Integer userid;
    
    private String username;
    
    private String realname;
    
    private Integer parentid;
    private String parentphone;
    private String parentname;
    
    private Integer salesman;
    
    private String salemanname;
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.id
     *
     * @return the value of c_cash_usdt_logs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.id
     *
     * @param id the value for c_cash_usdt_logs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.cid
     *
     * @return the value of c_cash_usdt_logs.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.cid
     *
     * @param cid the value for c_cash_usdt_logs.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.fromaddr
     *
     * @return the value of c_cash_usdt_logs.fromaddr
     *
     * @mbggenerated
     */
    public String getFromaddr() {
        return fromaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.fromaddr
     *
     * @param fromaddr the value for c_cash_usdt_logs.fromaddr
     *
     * @mbggenerated
     */
    public void setFromaddr(String fromaddr) {
        this.fromaddr = fromaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.money
     *
     * @return the value of c_cash_usdt_logs.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.money
     *
     * @param money the value for c_cash_usdt_logs.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.tax
     *
     * @return the value of c_cash_usdt_logs.tax
     *
     * @mbggenerated
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.tax
     *
     * @param tax the value for c_cash_usdt_logs.tax
     *
     * @mbggenerated
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.realmoney
     *
     * @return the value of c_cash_usdt_logs.realmoney
     *
     * @mbggenerated
     */
    public BigDecimal getRealmoney() {
        return realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.realmoney
     *
     * @param realmoney the value for c_cash_usdt_logs.realmoney
     *
     * @mbggenerated
     */
    public void setRealmoney(BigDecimal realmoney) {
        this.realmoney = realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.toaddr
     *
     * @return the value of c_cash_usdt_logs.toaddr
     *
     * @mbggenerated
     */
    public String getToaddr() {
        return toaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.toaddr
     *
     * @param toaddr the value for c_cash_usdt_logs.toaddr
     *
     * @mbggenerated
     */
    public void setToaddr(String toaddr) {
        this.toaddr = toaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.status
     *
     * @return the value of c_cash_usdt_logs.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.status
     *
     * @param status the value for c_cash_usdt_logs.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.hashcode
     *
     * @return the value of c_cash_usdt_logs.hashcode
     *
     * @mbggenerated
     */
    public String getHashcode() {
        return hashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.hashcode
     *
     * @param hashcode the value for c_cash_usdt_logs.hashcode
     *
     * @mbggenerated
     */
    public void setHashcode(String hashcode) {
        this.hashcode = hashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.createtime
     *
     * @return the value of c_cash_usdt_logs.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.createtime
     *
     * @param createtime the value for c_cash_usdt_logs.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.checktime
     *
     * @return the value of c_cash_usdt_logs.checktime
     *
     * @mbggenerated
     */
    public Date getChecktime() {
        return checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.checktime
     *
     * @param checktime the value for c_cash_usdt_logs.checktime
     *
     * @mbggenerated
     */
    public void setChecktime(Date checktime) {
        this.checktime = checktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.checkid
     *
     * @return the value of c_cash_usdt_logs.checkid
     *
     * @mbggenerated
     */
    public Integer getCheckid() {
        return checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.checkid
     *
     * @param checkid the value for c_cash_usdt_logs.checkid
     *
     * @mbggenerated
     */
    public void setCheckid(Integer checkid) {
        this.checkid = checkid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.dztime
     *
     * @return the value of c_cash_usdt_logs.dztime
     *
     * @mbggenerated
     */
    public Date getDztime() {
        return dztime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.dztime
     *
     * @param dztime the value for c_cash_usdt_logs.dztime
     *
     * @mbggenerated
     */
    public void setDztime(Date dztime) {
        this.dztime = dztime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_cash_usdt_logs.dzstatus
     *
     * @return the value of c_cash_usdt_logs.dzstatus
     *
     * @mbggenerated
     */
    public Integer getDzstatus() {
        return dzstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_cash_usdt_logs.dzstatus
     *
     * @param dzstatus the value for c_cash_usdt_logs.dzstatus
     *
     * @mbggenerated
     */
    public void setDzstatus(Integer dzstatus) {
        this.dzstatus = dzstatus;
    }

	public String getChecker() {
		return checker;
	}

	public void setChecker(String checker) {
		this.checker = checker;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getParentphone() {
		return parentphone;
	}

	public void setParentphone(String parentphone) {
		this.parentphone = parentphone;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public Integer getSalesman() {
		return salesman;
	}

	public void setSalesman(Integer salesman) {
		this.salesman = salesman;
	}

	public String getSalemanname() {
		return salemanname;
	}

	public void setSalemanname(String salemanname) {
		this.salemanname = salemanname;
	}
    
    
}