package com.contract.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CContractOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_contract_order
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_contract_order
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table c_contract_order
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public CContractOrderExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_contract_order
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrdercodeIsNull() {
            addCriterion("ordercode is null");
            return (Criteria) this;
        }

        public Criteria andOrdercodeIsNotNull() {
            addCriterion("ordercode is not null");
            return (Criteria) this;
        }

        public Criteria andOrdercodeEqualTo(String value) {
            addCriterion("ordercode =", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotEqualTo(String value) {
            addCriterion("ordercode <>", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeGreaterThan(String value) {
            addCriterion("ordercode >", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeGreaterThanOrEqualTo(String value) {
            addCriterion("ordercode >=", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeLessThan(String value) {
            addCriterion("ordercode <", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeLessThanOrEqualTo(String value) {
            addCriterion("ordercode <=", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeLike(String value) {
            addCriterion("ordercode like", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotLike(String value) {
            addCriterion("ordercode not like", value, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeIn(List<String> values) {
            addCriterion("ordercode in", values, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotIn(List<String> values) {
            addCriterion("ordercode not in", values, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeBetween(String value1, String value2) {
            addCriterion("ordercode between", value1, value2, "ordercode");
            return (Criteria) this;
        }

        public Criteria andOrdercodeNotBetween(String value1, String value2) {
            addCriterion("ordercode not between", value1, value2, "ordercode");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andRealmoneyIsNull() {
            addCriterion("realmoney is null");
            return (Criteria) this;
        }

        public Criteria andRealmoneyIsNotNull() {
            addCriterion("realmoney is not null");
            return (Criteria) this;
        }

        public Criteria andRealmoneyEqualTo(BigDecimal value) {
            addCriterion("realmoney =", value, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyNotEqualTo(BigDecimal value) {
            addCriterion("realmoney <>", value, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyGreaterThan(BigDecimal value) {
            addCriterion("realmoney >", value, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("realmoney >=", value, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyLessThan(BigDecimal value) {
            addCriterion("realmoney <", value, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("realmoney <=", value, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyIn(List<BigDecimal> values) {
            addCriterion("realmoney in", values, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyNotIn(List<BigDecimal> values) {
            addCriterion("realmoney not in", values, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("realmoney between", value1, value2, "realmoney");
            return (Criteria) this;
        }

        public Criteria andRealmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("realmoney not between", value1, value2, "realmoney");
            return (Criteria) this;
        }

        public Criteria andGearingIsNull() {
            addCriterion("gearing is null");
            return (Criteria) this;
        }

        public Criteria andGearingIsNotNull() {
            addCriterion("gearing is not null");
            return (Criteria) this;
        }

        public Criteria andGearingEqualTo(Integer value) {
            addCriterion("gearing =", value, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingNotEqualTo(Integer value) {
            addCriterion("gearing <>", value, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingGreaterThan(Integer value) {
            addCriterion("gearing >", value, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingGreaterThanOrEqualTo(Integer value) {
            addCriterion("gearing >=", value, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingLessThan(Integer value) {
            addCriterion("gearing <", value, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingLessThanOrEqualTo(Integer value) {
            addCriterion("gearing <=", value, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingIn(List<Integer> values) {
            addCriterion("gearing in", values, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingNotIn(List<Integer> values) {
            addCriterion("gearing not in", values, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingBetween(Integer value1, Integer value2) {
            addCriterion("gearing between", value1, value2, "gearing");
            return (Criteria) this;
        }

        public Criteria andGearingNotBetween(Integer value1, Integer value2) {
            addCriterion("gearing not between", value1, value2, "gearing");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andBuypriceIsNull() {
            addCriterion("buyprice is null");
            return (Criteria) this;
        }

        public Criteria andBuypriceIsNotNull() {
            addCriterion("buyprice is not null");
            return (Criteria) this;
        }

        public Criteria andBuypriceEqualTo(BigDecimal value) {
            addCriterion("buyprice =", value, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceNotEqualTo(BigDecimal value) {
            addCriterion("buyprice <>", value, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceGreaterThan(BigDecimal value) {
            addCriterion("buyprice >", value, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("buyprice >=", value, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceLessThan(BigDecimal value) {
            addCriterion("buyprice <", value, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("buyprice <=", value, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceIn(List<BigDecimal> values) {
            addCriterion("buyprice in", values, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceNotIn(List<BigDecimal> values) {
            addCriterion("buyprice not in", values, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buyprice between", value1, value2, "buyprice");
            return (Criteria) this;
        }

        public Criteria andBuypriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("buyprice not between", value1, value2, "buyprice");
            return (Criteria) this;
        }

        public Criteria andCoinIsNull() {
            addCriterion("coin is null");
            return (Criteria) this;
        }

        public Criteria andCoinIsNotNull() {
            addCriterion("coin is not null");
            return (Criteria) this;
        }

        public Criteria andCoinEqualTo(String value) {
            addCriterion("coin =", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotEqualTo(String value) {
            addCriterion("coin <>", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinGreaterThan(String value) {
            addCriterion("coin >", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinGreaterThanOrEqualTo(String value) {
            addCriterion("coin >=", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLessThan(String value) {
            addCriterion("coin <", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLessThanOrEqualTo(String value) {
            addCriterion("coin <=", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinLike(String value) {
            addCriterion("coin like", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotLike(String value) {
            addCriterion("coin not like", value, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinIn(List<String> values) {
            addCriterion("coin in", values, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotIn(List<String> values) {
            addCriterion("coin not in", values, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinBetween(String value1, String value2) {
            addCriterion("coin between", value1, value2, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinNotBetween(String value1, String value2) {
            addCriterion("coin not between", value1, value2, "coin");
            return (Criteria) this;
        }

        public Criteria andCoinnumIsNull() {
            addCriterion("coinnum is null");
            return (Criteria) this;
        }

        public Criteria andCoinnumIsNotNull() {
            addCriterion("coinnum is not null");
            return (Criteria) this;
        }

        public Criteria andCoinnumEqualTo(BigDecimal value) {
            addCriterion("coinnum =", value, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumNotEqualTo(BigDecimal value) {
            addCriterion("coinnum <>", value, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumGreaterThan(BigDecimal value) {
            addCriterion("coinnum >", value, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("coinnum >=", value, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumLessThan(BigDecimal value) {
            addCriterion("coinnum <", value, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("coinnum <=", value, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumIn(List<BigDecimal> values) {
            addCriterion("coinnum in", values, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumNotIn(List<BigDecimal> values) {
            addCriterion("coinnum not in", values, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coinnum between", value1, value2, "coinnum");
            return (Criteria) this;
        }

        public Criteria andCoinnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("coinnum not between", value1, value2, "coinnum");
            return (Criteria) this;
        }

        public Criteria andStoppriceIsNull() {
            addCriterion("stopprice is null");
            return (Criteria) this;
        }

        public Criteria andStoppriceIsNotNull() {
            addCriterion("stopprice is not null");
            return (Criteria) this;
        }

        public Criteria andStoppriceEqualTo(BigDecimal value) {
            addCriterion("stopprice =", value, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceNotEqualTo(BigDecimal value) {
            addCriterion("stopprice <>", value, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceGreaterThan(BigDecimal value) {
            addCriterion("stopprice >", value, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stopprice >=", value, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceLessThan(BigDecimal value) {
            addCriterion("stopprice <", value, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stopprice <=", value, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceIn(List<BigDecimal> values) {
            addCriterion("stopprice in", values, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceNotIn(List<BigDecimal> values) {
            addCriterion("stopprice not in", values, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stopprice between", value1, value2, "stopprice");
            return (Criteria) this;
        }

        public Criteria andStoppriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stopprice not between", value1, value2, "stopprice");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andStoptimeIsNull() {
            addCriterion("stoptime is null");
            return (Criteria) this;
        }

        public Criteria andStoptimeIsNotNull() {
            addCriterion("stoptime is not null");
            return (Criteria) this;
        }

        public Criteria andStoptimeEqualTo(Date value) {
            addCriterion("stoptime =", value, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeNotEqualTo(Date value) {
            addCriterion("stoptime <>", value, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeGreaterThan(Date value) {
            addCriterion("stoptime >", value, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("stoptime >=", value, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeLessThan(Date value) {
            addCriterion("stoptime <", value, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeLessThanOrEqualTo(Date value) {
            addCriterion("stoptime <=", value, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeIn(List<Date> values) {
            addCriterion("stoptime in", values, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeNotIn(List<Date> values) {
            addCriterion("stoptime not in", values, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeBetween(Date value1, Date value2) {
            addCriterion("stoptime between", value1, value2, "stoptime");
            return (Criteria) this;
        }

        public Criteria andStoptimeNotBetween(Date value1, Date value2) {
            addCriterion("stoptime not between", value1, value2, "stoptime");
            return (Criteria) this;
        }

        public Criteria andTaxIsNull() {
            addCriterion("tax is null");
            return (Criteria) this;
        }

        public Criteria andTaxIsNotNull() {
            addCriterion("tax is not null");
            return (Criteria) this;
        }

        public Criteria andTaxEqualTo(BigDecimal value) {
            addCriterion("tax =", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotEqualTo(BigDecimal value) {
            addCriterion("tax <>", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxGreaterThan(BigDecimal value) {
            addCriterion("tax >", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("tax >=", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxLessThan(BigDecimal value) {
            addCriterion("tax <", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxLessThanOrEqualTo(BigDecimal value) {
            addCriterion("tax <=", value, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxIn(List<BigDecimal> values) {
            addCriterion("tax in", values, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotIn(List<BigDecimal> values) {
            addCriterion("tax not in", values, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax between", value1, value2, "tax");
            return (Criteria) this;
        }

        public Criteria andTaxNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("tax not between", value1, value2, "tax");
            return (Criteria) this;
        }

        public Criteria andRatesIsNull() {
            addCriterion("rates is null");
            return (Criteria) this;
        }

        public Criteria andRatesIsNotNull() {
            addCriterion("rates is not null");
            return (Criteria) this;
        }

        public Criteria andRatesEqualTo(BigDecimal value) {
            addCriterion("rates =", value, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesNotEqualTo(BigDecimal value) {
            addCriterion("rates <>", value, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesGreaterThan(BigDecimal value) {
            addCriterion("rates >", value, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("rates >=", value, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesLessThan(BigDecimal value) {
            addCriterion("rates <", value, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("rates <=", value, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesIn(List<BigDecimal> values) {
            addCriterion("rates in", values, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesNotIn(List<BigDecimal> values) {
            addCriterion("rates not in", values, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rates between", value1, value2, "rates");
            return (Criteria) this;
        }

        public Criteria andRatesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("rates not between", value1, value2, "rates");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andAutomoneyIsNull() {
            addCriterion("automoney is null");
            return (Criteria) this;
        }

        public Criteria andAutomoneyIsNotNull() {
            addCriterion("automoney is not null");
            return (Criteria) this;
        }

        public Criteria andAutomoneyEqualTo(BigDecimal value) {
            addCriterion("automoney =", value, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyNotEqualTo(BigDecimal value) {
            addCriterion("automoney <>", value, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyGreaterThan(BigDecimal value) {
            addCriterion("automoney >", value, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("automoney >=", value, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyLessThan(BigDecimal value) {
            addCriterion("automoney <", value, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("automoney <=", value, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyIn(List<BigDecimal> values) {
            addCriterion("automoney in", values, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyNotIn(List<BigDecimal> values) {
            addCriterion("automoney not in", values, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("automoney between", value1, value2, "automoney");
            return (Criteria) this;
        }

        public Criteria andAutomoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("automoney not between", value1, value2, "automoney");
            return (Criteria) this;
        }

        public Criteria andSettleflagIsNull() {
            addCriterion("settleflag is null");
            return (Criteria) this;
        }

        public Criteria andSettleflagIsNotNull() {
            addCriterion("settleflag is not null");
            return (Criteria) this;
        }

        public Criteria andSettleflagEqualTo(Integer value) {
            addCriterion("settleflag =", value, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagNotEqualTo(Integer value) {
            addCriterion("settleflag <>", value, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagGreaterThan(Integer value) {
            addCriterion("settleflag >", value, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagGreaterThanOrEqualTo(Integer value) {
            addCriterion("settleflag >=", value, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagLessThan(Integer value) {
            addCriterion("settleflag <", value, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagLessThanOrEqualTo(Integer value) {
            addCriterion("settleflag <=", value, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagIn(List<Integer> values) {
            addCriterion("settleflag in", values, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagNotIn(List<Integer> values) {
            addCriterion("settleflag not in", values, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagBetween(Integer value1, Integer value2) {
            addCriterion("settleflag between", value1, value2, "settleflag");
            return (Criteria) this;
        }

        public Criteria andSettleflagNotBetween(Integer value1, Integer value2) {
            addCriterion("settleflag not between", value1, value2, "settleflag");
            return (Criteria) this;
        }

        public Criteria andOuttypeIsNull() {
            addCriterion("outtype is null");
            return (Criteria) this;
        }

        public Criteria andOuttypeIsNotNull() {
            addCriterion("outtype is not null");
            return (Criteria) this;
        }

        public Criteria andOuttypeEqualTo(Integer value) {
            addCriterion("outtype =", value, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeNotEqualTo(Integer value) {
            addCriterion("outtype <>", value, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeGreaterThan(Integer value) {
            addCriterion("outtype >", value, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("outtype >=", value, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeLessThan(Integer value) {
            addCriterion("outtype <", value, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeLessThanOrEqualTo(Integer value) {
            addCriterion("outtype <=", value, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeIn(List<Integer> values) {
            addCriterion("outtype in", values, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeNotIn(List<Integer> values) {
            addCriterion("outtype not in", values, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeBetween(Integer value1, Integer value2) {
            addCriterion("outtype between", value1, value2, "outtype");
            return (Criteria) this;
        }

        public Criteria andOuttypeNotBetween(Integer value1, Integer value2) {
            addCriterion("outtype not between", value1, value2, "outtype");
            return (Criteria) this;
        }

        public Criteria andStopwinIsNull() {
            addCriterion("stopwin is null");
            return (Criteria) this;
        }

        public Criteria andStopwinIsNotNull() {
            addCriterion("stopwin is not null");
            return (Criteria) this;
        }

        public Criteria andStopwinEqualTo(BigDecimal value) {
            addCriterion("stopwin =", value, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinNotEqualTo(BigDecimal value) {
            addCriterion("stopwin <>", value, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinGreaterThan(BigDecimal value) {
            addCriterion("stopwin >", value, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stopwin >=", value, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinLessThan(BigDecimal value) {
            addCriterion("stopwin <", value, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stopwin <=", value, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinIn(List<BigDecimal> values) {
            addCriterion("stopwin in", values, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinNotIn(List<BigDecimal> values) {
            addCriterion("stopwin not in", values, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stopwin between", value1, value2, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopwinNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stopwin not between", value1, value2, "stopwin");
            return (Criteria) this;
        }

        public Criteria andStopdonatIsNull() {
            addCriterion("stopdonat is null");
            return (Criteria) this;
        }

        public Criteria andStopdonatIsNotNull() {
            addCriterion("stopdonat is not null");
            return (Criteria) this;
        }

        public Criteria andStopdonatEqualTo(BigDecimal value) {
            addCriterion("stopdonat =", value, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatNotEqualTo(BigDecimal value) {
            addCriterion("stopdonat <>", value, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatGreaterThan(BigDecimal value) {
            addCriterion("stopdonat >", value, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stopdonat >=", value, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatLessThan(BigDecimal value) {
            addCriterion("stopdonat <", value, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stopdonat <=", value, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatIn(List<BigDecimal> values) {
            addCriterion("stopdonat in", values, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatNotIn(List<BigDecimal> values) {
            addCriterion("stopdonat not in", values, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stopdonat between", value1, value2, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andStopdonatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stopdonat not between", value1, value2, "stopdonat");
            return (Criteria) this;
        }

        public Criteria andSpreadIsNull() {
            addCriterion("spread is null");
            return (Criteria) this;
        }

        public Criteria andSpreadIsNotNull() {
            addCriterion("spread is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadEqualTo(BigDecimal value) {
            addCriterion("spread =", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotEqualTo(BigDecimal value) {
            addCriterion("spread <>", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadGreaterThan(BigDecimal value) {
            addCriterion("spread >", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("spread >=", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadLessThan(BigDecimal value) {
            addCriterion("spread <", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadLessThanOrEqualTo(BigDecimal value) {
            addCriterion("spread <=", value, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadIn(List<BigDecimal> values) {
            addCriterion("spread in", values, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotIn(List<BigDecimal> values) {
            addCriterion("spread not in", values, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spread between", value1, value2, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spread not between", value1, value2, "spread");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyIsNull() {
            addCriterion("spreadmoney is null");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyIsNotNull() {
            addCriterion("spreadmoney is not null");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyEqualTo(BigDecimal value) {
            addCriterion("spreadmoney =", value, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyNotEqualTo(BigDecimal value) {
            addCriterion("spreadmoney <>", value, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyGreaterThan(BigDecimal value) {
            addCriterion("spreadmoney >", value, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("spreadmoney >=", value, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyLessThan(BigDecimal value) {
            addCriterion("spreadmoney <", value, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("spreadmoney <=", value, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyIn(List<BigDecimal> values) {
            addCriterion("spreadmoney in", values, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyNotIn(List<BigDecimal> values) {
            addCriterion("spreadmoney not in", values, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spreadmoney between", value1, value2, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andSpreadmoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("spreadmoney not between", value1, value2, "spreadmoney");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIsNull() {
            addCriterion("ordertype is null");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIsNotNull() {
            addCriterion("ordertype is not null");
            return (Criteria) this;
        }

        public Criteria andOrdertypeEqualTo(Integer value) {
            addCriterion("ordertype =", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotEqualTo(Integer value) {
            addCriterion("ordertype <>", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeGreaterThan(Integer value) {
            addCriterion("ordertype >", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ordertype >=", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLessThan(Integer value) {
            addCriterion("ordertype <", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeLessThanOrEqualTo(Integer value) {
            addCriterion("ordertype <=", value, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeIn(List<Integer> values) {
            addCriterion("ordertype in", values, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotIn(List<Integer> values) {
            addCriterion("ordertype not in", values, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeBetween(Integer value1, Integer value2) {
            addCriterion("ordertype between", value1, value2, "ordertype");
            return (Criteria) this;
        }

        public Criteria andOrdertypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ordertype not between", value1, value2, "ordertype");
            return (Criteria) this;
        }

        public Criteria andRunTimeIsNull() {
            addCriterion("run_time is null");
            return (Criteria) this;
        }

        public Criteria andRunTimeIsNotNull() {
            addCriterion("run_time is not null");
            return (Criteria) this;
        }

        public Criteria andRunTimeEqualTo(Integer value) {
            addCriterion("run_time =", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotEqualTo(Integer value) {
            addCriterion("run_time <>", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeGreaterThan(Integer value) {
            addCriterion("run_time >", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("run_time >=", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLessThan(Integer value) {
            addCriterion("run_time <", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeLessThanOrEqualTo(Integer value) {
            addCriterion("run_time <=", value, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeIn(List<Integer> values) {
            addCriterion("run_time in", values, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotIn(List<Integer> values) {
            addCriterion("run_time not in", values, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeBetween(Integer value1, Integer value2) {
            addCriterion("run_time between", value1, value2, "runTime");
            return (Criteria) this;
        }

        public Criteria andRunTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("run_time not between", value1, value2, "runTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_contract_order
     *
     * @mbg.generated do_not_delete_during_merge Mon Nov 09 17:25:45 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table c_contract_order
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}