package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.commons.lang3.StringUtils;

import com.contract.common.DateUtil;
import com.contract.service.Page;

public class CContractOrder extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6986311589277426187L;

	/**  */
    private Integer id;
 
    /** 订单号 */
    private String ordercode;

    /** 用户id */
    private Integer cid;

    /** 1开多 2开空 */
    private Integer type;

    /** 实际花费金额 */
    private BigDecimal realmoney;

    /** 杠杆倍数 */
    private Integer gearing;

    /** 杠杆放大金额 */
    private BigDecimal money;

    /** 买入价 市值 */
    private BigDecimal buyprice;

    /** 货币类型 见coin表 */
    private String coin;

    /** 持仓量 */
    private BigDecimal coinnum;

    /** 平仓价 市值 */
    private BigDecimal stopprice;

    /** 持仓时间 */
    private Date createtime;

    /** 平仓时间 */
    private Date stoptime;

    /** 手续费 */
    private BigDecimal tax;

    /** 利息 */
    private BigDecimal rates;

    /** 1持仓中 2已完成 */
    private Integer status;

    /** 自动爆仓价 */
    private BigDecimal automoney;

    /** -1未结算 1已结算 */
    private Integer settleflag;

    /** 1手动平仓 2自动爆仓 */
    private Integer outtype;

    /** 止盈价格 */
    private BigDecimal stopwin;

    /** 止损价格 */
    private BigDecimal stopdonat;

    /** 点差比例 */
    private BigDecimal spread=BigDecimal.ZERO;
    
    /** 点差金额 */
    private BigDecimal spreadmoney;

    /** 备注 */
    private String remark;

    /** 持仓时长 单位s */
    private Integer runTime;

    public Integer getRunLength() {
        return runLength;
    }

    public void setRunLength(Integer runLength) {
        this.runLength = runLength;
    }

    /** 持仓时长固定值 */
    private Integer runLength;

    public Integer getOrdertype() {
        return ordertype;
    }

    public void setOrdertype(Integer ordertype) {
        this.ordertype = ordertype;
    }

    private Integer ordertype;
    private String timestr;
    private String coinname;
    
    private Integer userid;
    private String username;
    private String login;
    
    private String parentname;
    private Integer parentid;
    
    private String realname;
    
    private Integer salesman;
    
    private Integer identity;
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.id
     *
     * @return the value of c_contract_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.id
     *
     * @param id the value for c_contract_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.ordercode
     *
     * @return the value of c_contract_order.ordercode
     *
     * @mbggenerated
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.ordercode
     *
     * @param ordercode the value for c_contract_order.ordercode
     *
     * @mbggenerated
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.cid
     *
     * @return the value of c_contract_order.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.cid
     *
     * @param cid the value for c_contract_order.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.type
     *
     * @return the value of c_contract_order.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.type
     *
     * @param type the value for c_contract_order.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.realmoney
     *
     * @return the value of c_contract_order.realmoney
     *
     * @mbggenerated
     */
    public BigDecimal getRealmoney() {
        return realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.realmoney
     *
     * @param realmoney the value for c_contract_order.realmoney
     *
     * @mbggenerated
     */
    public void setRealmoney(BigDecimal realmoney) {
        this.realmoney = realmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.gearing
     *
     * @return the value of c_contract_order.gearing
     *
     * @mbggenerated
     */
    public Integer getGearing() {
        return gearing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.gearing
     *
     * @param gearing the value for c_contract_order.gearing
     *
     * @mbggenerated
     */
    public void setGearing(Integer gearing) {
        this.gearing = gearing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.money
     *
     * @return the value of c_contract_order.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.money
     *
     * @param money the value for c_contract_order.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.buyprice
     *
     * @return the value of c_contract_order.buyprice
     *
     * @mbggenerated
     */
    public BigDecimal getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.buyprice
     *
     * @param buyprice the value for c_contract_order.buyprice
     *
     * @mbggenerated
     */
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.coin
     *
     * @return the value of c_contract_order.coin
     *
     * @mbggenerated
     */
    public String getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.coin
     *
     * @param coin the value for c_contract_order.coin
     *
     * @mbggenerated
     */
    public void setCoin(String coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.coinnum
     *
     * @return the value of c_contract_order.coinnum
     *
     * @mbggenerated
     */
    public BigDecimal getCoinnum() {
        return coinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.coinnum
     *
     * @param coinnum the value for c_contract_order.coinnum
     *
     * @mbggenerated
     */
    public void setCoinnum(BigDecimal coinnum) {
        this.coinnum = coinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.stopprice
     *
     * @return the value of c_contract_order.stopprice
     *
     * @mbggenerated
     */
    public BigDecimal getStopprice() {
        return stopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.stopprice
     *
     * @param stopprice the value for c_contract_order.stopprice
     *
     * @mbggenerated
     */
    public void setStopprice(BigDecimal stopprice) {
        this.stopprice = stopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.createtime
     *
     * @return the value of c_contract_order.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.createtime
     *
     * @param createtime the value for c_contract_order.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.stoptime
     *
     * @return the value of c_contract_order.stoptime
     *
     * @mbggenerated
     */
    public Date getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.stoptime
     *
     * @param stoptime the value for c_contract_order.stoptime
     *
     * @mbggenerated
     */
    public void setStoptime(Date stoptime) {
        this.stoptime = stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.tax
     *
     * @return the value of c_contract_order.tax
     *
     * @mbggenerated
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.tax
     *
     * @param tax the value for c_contract_order.tax
     *
     * @mbggenerated
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.rates
     *
     * @return the value of c_contract_order.rates
     *
     * @mbggenerated
     */
    public BigDecimal getRates() {
        return rates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.rates
     *
     * @param rates the value for c_contract_order.rates
     *
     * @mbggenerated
     */
    public void setRates(BigDecimal rates) {
        this.rates = rates;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.status
     *
     * @return the value of c_contract_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.status
     *
     * @param status the value for c_contract_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.automoney
     *
     * @return the value of c_contract_order.automoney
     *
     * @mbggenerated
     */
    public BigDecimal getAutomoney() {
        return automoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.automoney
     *
     * @param automoney the value for c_contract_order.automoney
     *
     * @mbggenerated
     */
    public void setAutomoney(BigDecimal automoney) {
        this.automoney = automoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.settleflag
     *
     * @return the value of c_contract_order.settleflag
     *
     * @mbggenerated
     */
    public Integer getSettleflag() {
        return settleflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.settleflag
     *
     * @param settleflag the value for c_contract_order.settleflag
     *
     * @mbggenerated
     */
    public void setSettleflag(Integer settleflag) {
        this.settleflag = settleflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.outtype
     *
     * @return the value of c_contract_order.outtype
     *
     * @mbggenerated
     */
    public Integer getOuttype() {
        return outtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.outtype
     *
     * @param outtype the value for c_contract_order.outtype
     *
     * @mbggenerated
     */
    public void setOuttype(Integer outtype) {
        this.outtype = outtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.stopwin
     *
     * @return the value of c_contract_order.stopwin
     *
     * @mbggenerated
     */
    public BigDecimal getStopwin() {
        return stopwin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.stopwin
     *
     * @param stopwin the value for c_contract_order.stopwin
     *
     * @mbggenerated
     */
    public void setStopwin(BigDecimal stopwin) {
        this.stopwin = stopwin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.stopdonat
     *
     * @return the value of c_contract_order.stopdonat
     *
     * @mbggenerated
     */
    public BigDecimal getStopdonat() {
        return stopdonat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.stopdonat
     *
     * @param stopdonat the value for c_contract_order.stopdonat
     *
     * @mbggenerated
     */
    public void setStopdonat(BigDecimal stopdonat) {
        this.stopdonat = stopdonat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_contract_order.spread
     *
     * @return the value of c_contract_order.spread
     *
     * @mbggenerated
     */
    public BigDecimal getSpread() {
        return spread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_contract_order.spread
     *
     * @param spread the value for c_contract_order.spread
     *
     * @mbggenerated
     */
    public void setSpread(BigDecimal spread) {
        this.spread = spread;
    }

	public String getTimestr() {
		if(createtime!=null) {
			timestr=DateUtil.toDateString(createtime,"yyyy-MM-dd HH:mm:ss");
		}
		return timestr;
	}

	public String getCoinname() {
		if(!StringUtils.isEmpty(coin)) {
			coinname=coin.replace("_", "/").toUpperCase();
		}
		return coinname;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public BigDecimal getSpreadmoney() {
		return spreadmoney;
	}

	public void setSpreadmoney(BigDecimal spreadmoney) {
		this.spreadmoney = spreadmoney;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Integer getSalesman() {
		return salesman;
	}

	public void setSalesman(Integer salesman) {
		this.salesman = salesman;
	}

	public Integer getIdentity() {
		return identity;
	}

	public void setIdentity(Integer identity) {
		this.identity = identity;
	}

    public Integer getRunTime() {
        return runTime;
    }

    public void setRunTime(Integer runTime) {
        this.runTime = runTime;
    }
}