package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.contract.dto.ReportDto;
import com.contract.service.Page;

public class CCustomer extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = 2097732705738693538L;

	/**  */
    private Integer id;

    /** 手机号 */
    private String phone;

    /** 密码 */
    private String password;

    /** 交易密码 */
    private String payword;

    /** 邀请码 */
    private String invitationcode;

    /** 真实名称 */
    private String realname;

    /** 身份证 */
    private String idcard;
    
    /** 身份证 */
    private String cardurls;

    /** 等级id */
    private Integer levelid;

    /**  */
    private Date createtime;

    /** 0有效 -1无效 */
    private Integer status;

    /** 推荐人 */
    private Integer parentid;

    /** 接点人 */
    private Integer lastid;

    /** 推荐代数 */
    private Integer layer;

    /** 分享二维码 */
    private String qrurl;

    /** -1未激活  0激活 */
    private Integer isvalid;

    /** 1未认证 2审核中 3审核通过 */
    private Integer authflag;

    /** 操作员id */
    private Integer userid;

    /** 业务员id */
    private Integer salesman;

    /** 是否可以提现 0可以 -1不行 */
    private Integer cancash;

    /** 0是业务员 -1不是业务员 */
    private Integer salesflag;
    
    /**
     * 1会员 2业务员 3模拟账号
     */
    private Integer identity;

    /** 推荐节点网 */
    private String pushgenes;
    
    private String parentname;
    
    /**
     * 业务员
     */
    private String salemanname;
    
    /**
     * 子公司
     */
    private String username;
    
    private ReportDto map;
    
    private BigDecimal balance;
    
    private BigDecimal zcbalance;

    private BigDecimal gdbalance;

    public BigDecimal getGdbalance() {
        return gdbalance;
    }

    public void setGdbalance(BigDecimal gdbalance) {
        this.gdbalance = gdbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.id
     *
     * @return the value of c_customer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.id
     *
     * @param id the value for c_customer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.phone
     *
     * @return the value of c_customer.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.phone
     *
     * @param phone the value for c_customer.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.password
     *
     * @return the value of c_customer.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.password
     *
     * @param password the value for c_customer.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.payword
     *
     * @return the value of c_customer.payword
     *
     * @mbggenerated
     */
    public String getPayword() {
        return payword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.payword
     *
     * @param payword the value for c_customer.payword
     *
     * @mbggenerated
     */
    public void setPayword(String payword) {
        this.payword = payword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.invitationcode
     *
     * @return the value of c_customer.invitationcode
     *
     * @mbggenerated
     */
    public String getInvitationcode() {
        return invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.invitationcode
     *
     * @param invitationcode the value for c_customer.invitationcode
     *
     * @mbggenerated
     */
    public void setInvitationcode(String invitationcode) {
        this.invitationcode = invitationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.realname
     *
     * @return the value of c_customer.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.realname
     *
     * @param realname the value for c_customer.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.idcard
     *
     * @return the value of c_customer.idcard
     *
     * @mbggenerated
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.idcard
     *
     * @param idcard the value for c_customer.idcard
     *
     * @mbggenerated
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.levelid
     *
     * @return the value of c_customer.levelid
     *
     * @mbggenerated
     */
    public Integer getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.levelid
     *
     * @param levelid the value for c_customer.levelid
     *
     * @mbggenerated
     */
    public void setLevelid(Integer levelid) {
        this.levelid = levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.createtime
     *
     * @return the value of c_customer.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.createtime
     *
     * @param createtime the value for c_customer.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.status
     *
     * @return the value of c_customer.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.status
     *
     * @param status the value for c_customer.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.parentid
     *
     * @return the value of c_customer.parentid
     *
     * @mbggenerated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.parentid
     *
     * @param parentid the value for c_customer.parentid
     *
     * @mbggenerated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.lastid
     *
     * @return the value of c_customer.lastid
     *
     * @mbggenerated
     */
    public Integer getLastid() {
        return lastid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.lastid
     *
     * @param lastid the value for c_customer.lastid
     *
     * @mbggenerated
     */
    public void setLastid(Integer lastid) {
        this.lastid = lastid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.layer
     *
     * @return the value of c_customer.layer
     *
     * @mbggenerated
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.layer
     *
     * @param layer the value for c_customer.layer
     *
     * @mbggenerated
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.qrurl
     *
     * @return the value of c_customer.qrurl
     *
     * @mbggenerated
     */
    public String getQrurl() {
        return qrurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.qrurl
     *
     * @param qrurl the value for c_customer.qrurl
     *
     * @mbggenerated
     */
    public void setQrurl(String qrurl) {
        this.qrurl = qrurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.isvalid
     *
     * @return the value of c_customer.isvalid
     *
     * @mbggenerated
     */
    public Integer getIsvalid() {
        return isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.isvalid
     *
     * @param isvalid the value for c_customer.isvalid
     *
     * @mbggenerated
     */
    public void setIsvalid(Integer isvalid) {
        this.isvalid = isvalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.authflag
     *
     * @return the value of c_customer.authflag
     *
     * @mbggenerated
     */
    public Integer getAuthflag() {
        return authflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.authflag
     *
     * @param authflag the value for c_customer.authflag
     *
     * @mbggenerated
     */
    public void setAuthflag(Integer authflag) {
        this.authflag = authflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.userid
     *
     * @return the value of c_customer.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.userid
     *
     * @param userid the value for c_customer.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.salesman
     *
     * @return the value of c_customer.salesman
     *
     * @mbggenerated
     */
    public Integer getSalesman() {
        return salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.salesman
     *
     * @param salesman the value for c_customer.salesman
     *
     * @mbggenerated
     */
    public void setSalesman(Integer salesman) {
        this.salesman = salesman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.cancash
     *
     * @return the value of c_customer.cancash
     *
     * @mbggenerated
     */
    public Integer getCancash() {
        return cancash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.cancash
     *
     * @param cancash the value for c_customer.cancash
     *
     * @mbggenerated
     */
    public void setCancash(Integer cancash) {
        this.cancash = cancash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.salesflag
     *
     * @return the value of c_customer.salesflag
     *
     * @mbggenerated
     */
    public Integer getSalesflag() {
        return salesflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.salesflag
     *
     * @param salesflag the value for c_customer.salesflag
     *
     * @mbggenerated
     */
    public void setSalesflag(Integer salesflag) {
        this.salesflag = salesflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_customer.pushgenes
     *
     * @return the value of c_customer.pushgenes
     *
     * @mbggenerated
     */
    public String getPushgenes() {
        return pushgenes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_customer.pushgenes
     *
     * @param pushgenes the value for c_customer.pushgenes
     *
     * @mbggenerated
     */
    public void setPushgenes(String pushgenes) {
        this.pushgenes = pushgenes;
    }

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public String getSalemanname() {
		return salemanname;
	}

	public void setSalemanname(String salemanname) {
		this.salemanname = salemanname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	

	public ReportDto getMap() {
		return map;
	}

	public void setMap(ReportDto map) {
		this.map = map;
	}

	public String getCardurls() {
		return cardurls;
	}

	public void setCardurls(String cardurls) {
		this.cardurls = cardurls;
	}

	public Integer getIdentity() {
		return identity;
	}

	public void setIdentity(Integer identity) {
		this.identity = identity;
	}

	public BigDecimal getBalance() {
		return balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public BigDecimal getZcbalance() {
		return zcbalance;
	}

	public void setZcbalance(BigDecimal zcbalance) {
		this.zcbalance = zcbalance;
	}
    
	
}