package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Coins {
    /** 货币名称 */
    private String coin;

    /** 名称 */
    private String name;

    /** 市场id，交易对 */
    private String symbol;

    /** 中币合并深度 */
    private String zbdepth;

    /** 上一次开盘价 */
    private BigDecimal openval;

    /**  */
    private Date updatetime;

    /** 开始点差比例 */
    private BigDecimal beginspread;

    /** 截止点差比例 */
    private BigDecimal stopspread;

    /**  */
    private Integer sort;

    /** -1未开启逐仓 0开启逐仓 */
    private Integer type;

    /** 逐仓自动平仓usdt金额 */
    private BigDecimal zcstopscale;

    /** 逐仓奖励倍数 */
    private BigDecimal zcscale;

    /** 逐仓开仓手续费 */
    private BigDecimal zctax;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.coin
     *
     * @return the value of coins.coin
     *
     * @mbggenerated
     */
    public String getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.coin
     *
     * @param coin the value for coins.coin
     *
     * @mbggenerated
     */
    public void setCoin(String coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.name
     *
     * @return the value of coins.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.name
     *
     * @param name the value for coins.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.symbol
     *
     * @return the value of coins.symbol
     *
     * @mbggenerated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.symbol
     *
     * @param symbol the value for coins.symbol
     *
     * @mbggenerated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.zbdepth
     *
     * @return the value of coins.zbdepth
     *
     * @mbggenerated
     */
    public String getZbdepth() {
        return zbdepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.zbdepth
     *
     * @param zbdepth the value for coins.zbdepth
     *
     * @mbggenerated
     */
    public void setZbdepth(String zbdepth) {
        this.zbdepth = zbdepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.openval
     *
     * @return the value of coins.openval
     *
     * @mbggenerated
     */
    public BigDecimal getOpenval() {
        return openval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.openval
     *
     * @param openval the value for coins.openval
     *
     * @mbggenerated
     */
    public void setOpenval(BigDecimal openval) {
        this.openval = openval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.updatetime
     *
     * @return the value of coins.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.updatetime
     *
     * @param updatetime the value for coins.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.beginspread
     *
     * @return the value of coins.beginspread
     *
     * @mbggenerated
     */
    public BigDecimal getBeginspread() {
        return beginspread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.beginspread
     *
     * @param beginspread the value for coins.beginspread
     *
     * @mbggenerated
     */
    public void setBeginspread(BigDecimal beginspread) {
        this.beginspread = beginspread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.stopspread
     *
     * @return the value of coins.stopspread
     *
     * @mbggenerated
     */
    public BigDecimal getStopspread() {
        return stopspread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.stopspread
     *
     * @param stopspread the value for coins.stopspread
     *
     * @mbggenerated
     */
    public void setStopspread(BigDecimal stopspread) {
        this.stopspread = stopspread;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.sort
     *
     * @return the value of coins.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.sort
     *
     * @param sort the value for coins.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.type
     *
     * @return the value of coins.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.type
     *
     * @param type the value for coins.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.zcstopscale
     *
     * @return the value of coins.zcstopscale
     *
     * @mbggenerated
     */
    public BigDecimal getZcstopscale() {
        return zcstopscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.zcstopscale
     *
     * @param zcstopscale the value for coins.zcstopscale
     *
     * @mbggenerated
     */
    public void setZcstopscale(BigDecimal zcstopscale) {
        this.zcstopscale = zcstopscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.zcscale
     *
     * @return the value of coins.zcscale
     *
     * @mbggenerated
     */
    public BigDecimal getZcscale() {
        return zcscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.zcscale
     *
     * @param zcscale the value for coins.zcscale
     *
     * @mbggenerated
     */
    public void setZcscale(BigDecimal zcscale) {
        this.zcscale = zcscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coins.zctax
     *
     * @return the value of coins.zctax
     *
     * @mbggenerated
     */
    public BigDecimal getZctax() {
        return zctax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coins.zctax
     *
     * @param zctax the value for coins.zctax
     *
     * @mbggenerated
     */
    public void setZctax(BigDecimal zctax) {
        this.zctax = zctax;
    }
}