package com.contract.entity;

import java.util.Date;

public class CPayChannel {
    /**  */
    private Integer id;

    /**  */
    private Integer cid;

    /** 类型 1支付宝 2微信 3银行卡 */
    private Integer type;

    /** 姓名 */
    private String name;

    /** 账号、银行卡号 */
    private String account;

    /** 支付收款码 */
    private String payqr;

    /** 开户行名称 */
    private String bankname;

    /**  */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.id
     *
     * @return the value of c_pay_channel.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.id
     *
     * @param id the value for c_pay_channel.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.cid
     *
     * @return the value of c_pay_channel.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.cid
     *
     * @param cid the value for c_pay_channel.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.type
     *
     * @return the value of c_pay_channel.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.type
     *
     * @param type the value for c_pay_channel.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.name
     *
     * @return the value of c_pay_channel.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.name
     *
     * @param name the value for c_pay_channel.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.account
     *
     * @return the value of c_pay_channel.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.account
     *
     * @param account the value for c_pay_channel.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.payqr
     *
     * @return the value of c_pay_channel.payqr
     *
     * @mbggenerated
     */
    public String getPayqr() {
        return payqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.payqr
     *
     * @param payqr the value for c_pay_channel.payqr
     *
     * @mbggenerated
     */
    public void setPayqr(String payqr) {
        this.payqr = payqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.bankname
     *
     * @return the value of c_pay_channel.bankname
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.bankname
     *
     * @param bankname the value for c_pay_channel.bankname
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_pay_channel.createtime
     *
     * @return the value of c_pay_channel.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_pay_channel.createtime
     *
     * @param createtime the value for c_pay_channel.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}