package com.contract.entity;

import java.math.BigDecimal;

public class CWallet {
    /**
     *
     */
    private Integer cid;

    /**
     * 钱包类型 见枚举 EOS ETH USDT BTH
     */
    private String type;

    /**
     * 钱包地址
     */
    private String addr;

    /**
     * 文件路径 ecr20的钱包路径
     */
    private String path;

    /**
     * 标签 修改为ecr20的钱包地址
     */
    private String label;

    /**
     * 密码
     */
    private String password;

    /**
     * 公钥
     */
    private String pubkey;

    /**
     * 私钥
     */
    private String prikey;

    /**
     * 钱包余额
     */
    private BigDecimal balance;

    /**
     * 逐仓金额
     */
    private BigDecimal zcbalance;

    /**
     * 节点编号
     */
    private String nodeid;

    /**
     * 二维码
     */
    private String qrurl;

    /**
     * erc20协议二维码
     */
    private String ecrqr;

    /**
     * 版本号
     */
    private Integer version;

    /**
     * 跟单金额
     */
    private BigDecimal gdbalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.cid
     *
     * @return the value of c_wallet.cid
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.cid
     *
     * @param cid the value for c_wallet.cid
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.type
     *
     * @return the value of c_wallet.type
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.type
     *
     * @param type the value for c_wallet.type
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.addr
     *
     * @return the value of c_wallet.addr
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getAddr() {
        return addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.addr
     *
     * @param addr the value for c_wallet.addr
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setAddr(String addr) {
        this.addr = addr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.path
     *
     * @return the value of c_wallet.path
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.path
     *
     * @param path the value for c_wallet.path
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.label
     *
     * @return the value of c_wallet.label
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.label
     *
     * @param label the value for c_wallet.label
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setLabel(String label) {
        this.label = label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.password
     *
     * @return the value of c_wallet.password
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.password
     *
     * @param password the value for c_wallet.password
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.pubkey
     *
     * @return the value of c_wallet.pubkey
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getPubkey() {
        return pubkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.pubkey
     *
     * @param pubkey the value for c_wallet.pubkey
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setPubkey(String pubkey) {
        this.pubkey = pubkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.prikey
     *
     * @return the value of c_wallet.prikey
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getPrikey() {
        return prikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.prikey
     *
     * @param prikey the value for c_wallet.prikey
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setPrikey(String prikey) {
        this.prikey = prikey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.balance
     *
     * @return the value of c_wallet.balance
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.balance
     *
     * @param balance the value for c_wallet.balance
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.zcbalance
     *
     * @return the value of c_wallet.zcbalance
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public BigDecimal getZcbalance() {
        return zcbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.zcbalance
     *
     * @param zcbalance the value for c_wallet.zcbalance
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setZcbalance(BigDecimal zcbalance) {
        this.zcbalance = zcbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.nodeid
     *
     * @return the value of c_wallet.nodeid
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getNodeid() {
        return nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.nodeid
     *
     * @param nodeid the value for c_wallet.nodeid
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setNodeid(String nodeid) {
        this.nodeid = nodeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.qrurl
     *
     * @return the value of c_wallet.qrurl
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getQrurl() {
        return qrurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.qrurl
     *
     * @param qrurl the value for c_wallet.qrurl
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setQrurl(String qrurl) {
        this.qrurl = qrurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.ecrqr
     *
     * @return the value of c_wallet.ecrqr
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public String getEcrqr() {
        return ecrqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.ecrqr
     *
     * @param ecrqr the value for c_wallet.ecrqr
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setEcrqr(String ecrqr) {
        this.ecrqr = ecrqr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.version
     *
     * @return the value of c_wallet.version
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.version
     *
     * @param version the value for c_wallet.version
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_wallet.gdbalance
     *
     * @return the value of c_wallet.gdbalance
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public BigDecimal getGdbalance() {
        return gdbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_wallet.gdbalance
     *
     * @param gdbalance the value for c_wallet.gdbalance
     *
     * @mbg.generated Tue Nov 10 16:27:30 CST 2020
     */
    public void setGdbalance(BigDecimal gdbalance) {
        this.gdbalance = gdbalance;
    }
}