package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

import com.contract.common.DateUtil;
import com.contract.service.Page;

public class CZcOrder extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3907427577620898434L;

	/**  */
    private Integer id;

    /** 用户id */
    private Integer cid;

    /** 订单号 */
    private String ordercode;

    /** 1开多 2开空 */
    private Integer type;

    /** 投入本金 */
    private BigDecimal capital;

    /** 手续费 */
    private BigDecimal tax;

    /** 买入价 */
    private BigDecimal buyprice;

    /** 平仓价 */
    private BigDecimal stopprice;

    /** 开仓时间 */
    private Date createtime;

    /** 货币对应coins表symbol字段 */
    private String coin;

    /** 平仓时间 */
    private Date stoptime;

    /** 实际收益 可以是负数 包含本金 */
    private BigDecimal reward;

    /** 逐仓理论爆仓金额 */
    private BigDecimal zcprice;

    /** 逐仓理论奖励倍数 */
    private BigDecimal zcscale;

    /** 描述 */
    private String remark;

    /** 止盈 */
    private BigDecimal stopwin;

    /** 止损 */
    private BigDecimal stopfail;

    /** 1逐仓中 2已平仓 */
    private Integer status;
    
    private String timestr;
    
    private Integer userid;
    
    private String login;
    
    private String realname;
    
    private String parentname;
    
    private Integer parentid;
    
    private String username;
    
    private Integer salesman;
    
    private Integer identity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.id
     *
     * @return the value of c_zc_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.id
     *
     * @param id the value for c_zc_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.cid
     *
     * @return the value of c_zc_order.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.cid
     *
     * @param cid the value for c_zc_order.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.ordercode
     *
     * @return the value of c_zc_order.ordercode
     *
     * @mbggenerated
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.ordercode
     *
     * @param ordercode the value for c_zc_order.ordercode
     *
     * @mbggenerated
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.type
     *
     * @return the value of c_zc_order.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.type
     *
     * @param type the value for c_zc_order.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.capital
     *
     * @return the value of c_zc_order.capital
     *
     * @mbggenerated
     */
    public BigDecimal getCapital() {
        return capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.capital
     *
     * @param capital the value for c_zc_order.capital
     *
     * @mbggenerated
     */
    public void setCapital(BigDecimal capital) {
        this.capital = capital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.tax
     *
     * @return the value of c_zc_order.tax
     *
     * @mbggenerated
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.tax
     *
     * @param tax the value for c_zc_order.tax
     *
     * @mbggenerated
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.buyprice
     *
     * @return the value of c_zc_order.buyprice
     *
     * @mbggenerated
     */
    public BigDecimal getBuyprice() {
        return buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.buyprice
     *
     * @param buyprice the value for c_zc_order.buyprice
     *
     * @mbggenerated
     */
    public void setBuyprice(BigDecimal buyprice) {
        this.buyprice = buyprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.stopprice
     *
     * @return the value of c_zc_order.stopprice
     *
     * @mbggenerated
     */
    public BigDecimal getStopprice() {
        return stopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.stopprice
     *
     * @param stopprice the value for c_zc_order.stopprice
     *
     * @mbggenerated
     */
    public void setStopprice(BigDecimal stopprice) {
        this.stopprice = stopprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.createtime
     *
     * @return the value of c_zc_order.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.createtime
     *
     * @param createtime the value for c_zc_order.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.coin
     *
     * @return the value of c_zc_order.coin
     *
     * @mbggenerated
     */
    public String getCoin() {
        return coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.coin
     *
     * @param coin the value for c_zc_order.coin
     *
     * @mbggenerated
     */
    public void setCoin(String coin) {
        this.coin = coin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.stoptime
     *
     * @return the value of c_zc_order.stoptime
     *
     * @mbggenerated
     */
    public Date getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.stoptime
     *
     * @param stoptime the value for c_zc_order.stoptime
     *
     * @mbggenerated
     */
    public void setStoptime(Date stoptime) {
        this.stoptime = stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.reward
     *
     * @return the value of c_zc_order.reward
     *
     * @mbggenerated
     */
    public BigDecimal getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.reward
     *
     * @param reward the value for c_zc_order.reward
     *
     * @mbggenerated
     */
    public void setReward(BigDecimal reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.zcprice
     *
     * @return the value of c_zc_order.zcprice
     *
     * @mbggenerated
     */
    public BigDecimal getZcprice() {
        return zcprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.zcprice
     *
     * @param zcprice the value for c_zc_order.zcprice
     *
     * @mbggenerated
     */
    public void setZcprice(BigDecimal zcprice) {
        this.zcprice = zcprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.zcscale
     *
     * @return the value of c_zc_order.zcscale
     *
     * @mbggenerated
     */
    public BigDecimal getZcscale() {
        return zcscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.zcscale
     *
     * @param zcscale the value for c_zc_order.zcscale
     *
     * @mbggenerated
     */
    public void setZcscale(BigDecimal zcscale) {
        this.zcscale = zcscale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.remark
     *
     * @return the value of c_zc_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.remark
     *
     * @param remark the value for c_zc_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.stopwin
     *
     * @return the value of c_zc_order.stopwin
     *
     * @mbggenerated
     */
    public BigDecimal getStopwin() {
        return stopwin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.stopwin
     *
     * @param stopwin the value for c_zc_order.stopwin
     *
     * @mbggenerated
     */
    public void setStopwin(BigDecimal stopwin) {
        this.stopwin = stopwin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.stopfail
     *
     * @return the value of c_zc_order.stopfail
     *
     * @mbggenerated
     */
    public BigDecimal getStopfail() {
        return stopfail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.stopfail
     *
     * @param stopfail the value for c_zc_order.stopfail
     *
     * @mbggenerated
     */
    public void setStopfail(BigDecimal stopfail) {
        this.stopfail = stopfail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_zc_order.status
     *
     * @return the value of c_zc_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_zc_order.status
     *
     * @param status the value for c_zc_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getTimestr() {
		if(createtime!=null) {
			timestr=DateUtil.toDateString(createtime, "yyyy-MM-dd HH:mm");
		}
		return timestr;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getSalesman() {
		return salesman;
	}

	public void setSalesman(Integer salesman) {
		this.salesman = salesman;
	}

	public Integer getIdentity() {
		return identity;
	}

	public void setIdentity(Integer identity) {
		this.identity = identity;
	}
    
    
}