package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 跟单日收益
 *
 */
public class GdOutput {
    /**
     * 
     */
    private Integer id;

    /**
     * 项目id
     */
    private Integer projectId;

    /**
     * 产出币种
     */
    private String outputCurrency;

    /**
     * 今日产出量
     */
    private BigDecimal capacity;

    /**
     * 产量日期yyyy-MM-dd
     */
    private String outputDate;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_output.id
     *
     * @return the value of documentary_output.id
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_output.id
     *
     * @param id the value for documentary_output.id
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_output.project_id
     *
     * @return the value of documentary_output.project_id
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_output.project_id
     *
     * @param projectId the value for documentary_output.project_id
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_output.output_currency
     *
     * @return the value of documentary_output.output_currency
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public String getOutputCurrency() {
        return outputCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_output.output_currency
     *
     * @param outputCurrency the value for documentary_output.output_currency
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public void setOutputCurrency(String outputCurrency) {
        this.outputCurrency = outputCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_output.capacity
     *
     * @return the value of documentary_output.capacity
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_output.capacity
     *
     * @param capacity the value for documentary_output.capacity
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public void setCapacity(BigDecimal capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_output.output_date
     *
     * @return the value of documentary_output.output_date
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public String getOutputDate() {
        return outputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_output.output_date
     *
     * @param outputDate the value for documentary_output.output_date
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public void setOutputDate(String outputDate) {
        this.outputDate = outputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_output.create_time
     *
     * @return the value of documentary_output.create_time
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_output.create_time
     *
     * @param createTime the value for documentary_output.create_time
     *
     * @mbg.generated Tue Nov 10 11:00:52 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}