package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 跟单分类
 *
 */
public class GdProject {
    /**
     *
     */
    private Integer id;

    /**
     * 算力每日产出的币种
     */
    private String outputCurrency;

    /**
     * 购买算力的货币
     */
    private String quoteCurrency;

    /**
     * 跟单价格
     */
    private BigDecimal price;

    /**
     * 每日产出下限
     */
    private BigDecimal outputFloor;

    /**
     * 每日产出上限
     */
    private BigDecimal outputUpper;

    /**
     * 运行状态 1未开始2启动3停止
     */
    private String runStatus;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * 修改时间
     */
    private Date modifyTime;

    /**
     * 跟单详情描述
     */
    private String particular;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.id
     *
     * @return the value of documentary_project.id
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.id
     *
     * @param id the value for documentary_project.id
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.output_currency
     *
     * @return the value of documentary_project.output_currency
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public String getOutputCurrency() {
        return outputCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.output_currency
     *
     * @param outputCurrency the value for documentary_project.output_currency
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setOutputCurrency(String outputCurrency) {
        this.outputCurrency = outputCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.quote_currency
     *
     * @return the value of documentary_project.quote_currency
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public String getQuoteCurrency() {
        return quoteCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.quote_currency
     *
     * @param quoteCurrency the value for documentary_project.quote_currency
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setQuoteCurrency(String quoteCurrency) {
        this.quoteCurrency = quoteCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.price
     *
     * @return the value of documentary_project.price
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.price
     *
     * @param price the value for documentary_project.price
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.output_floor
     *
     * @return the value of documentary_project.output_floor
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public BigDecimal getOutputFloor() {
        return outputFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.output_floor
     *
     * @param outputFloor the value for documentary_project.output_floor
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setOutputFloor(BigDecimal outputFloor) {
        this.outputFloor = outputFloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.output_upper
     *
     * @return the value of documentary_project.output_upper
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public BigDecimal getOutputUpper() {
        return outputUpper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.output_upper
     *
     * @param outputUpper the value for documentary_project.output_upper
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setOutputUpper(BigDecimal outputUpper) {
        this.outputUpper = outputUpper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.run_status
     *
     * @return the value of documentary_project.run_status
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public String getRunStatus() {
        return runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.run_status
     *
     * @param runStatus the value for documentary_project.run_status
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setRunStatus(String runStatus) {
        this.runStatus = runStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.create_time
     *
     * @return the value of documentary_project.create_time
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.create_time
     *
     * @param createTime the value for documentary_project.create_time
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.modify_time
     *
     * @return the value of documentary_project.modify_time
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.modify_time
     *
     * @param modifyTime the value for documentary_project.modify_time
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column documentary_project.particular
     *
     * @return the value of documentary_project.particular
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public String getParticular() {
        return particular;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column documentary_project.particular
     *
     * @param particular the value for documentary_project.particular
     *
     * @mbg.generated Tue Nov 10 11:28:14 CST 2020
     */
    public void setParticular(String particular) {
        this.particular = particular;
    }
}