package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 * 团队奖励表
 *
 */
public class GdTeamBonus {
    /**
     * 
     */
    private Integer id;

    /**
     * 用户id
     */
    private Integer memberId;

    /**
     * 人员等级
     */
    private String level;

    /**
     * 获得的团队奖励
     */
    private BigDecimal teamBonus;

    /**
     * 当前等级奖励率
     */
    private BigDecimal bonusRate;

    /**
     * 伞下人员日总产量
     */
    private BigDecimal subBonusBase;

    /**
     * 分红日期
     */
    private String bonusDate;

    /**
     * 创建时间
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.id
     *
     * @return the value of gd_team_bonus.id
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.id
     *
     * @param id the value for gd_team_bonus.id
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.member_id
     *
     * @return the value of gd_team_bonus.member_id
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.member_id
     *
     * @param memberId the value for gd_team_bonus.member_id
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.Level
     *
     * @return the value of gd_team_bonus.Level
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.Level
     *
     * @param level the value for gd_team_bonus.Level
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.team_bonus
     *
     * @return the value of gd_team_bonus.team_bonus
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public BigDecimal getTeamBonus() {
        return teamBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.team_bonus
     *
     * @param teamBonus the value for gd_team_bonus.team_bonus
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setTeamBonus(BigDecimal teamBonus) {
        this.teamBonus = teamBonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.bonus_rate
     *
     * @return the value of gd_team_bonus.bonus_rate
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public BigDecimal getBonusRate() {
        return bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.bonus_rate
     *
     * @param bonusRate the value for gd_team_bonus.bonus_rate
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setBonusRate(BigDecimal bonusRate) {
        this.bonusRate = bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.sub_bonus_base
     *
     * @return the value of gd_team_bonus.sub_bonus_base
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public BigDecimal getSubBonusBase() {
        return subBonusBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.sub_bonus_base
     *
     * @param subBonusBase the value for gd_team_bonus.sub_bonus_base
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setSubBonusBase(BigDecimal subBonusBase) {
        this.subBonusBase = subBonusBase;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.bonus_date
     *
     * @return the value of gd_team_bonus.bonus_date
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public String getBonusDate() {
        return bonusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.bonus_date
     *
     * @param bonusDate the value for gd_team_bonus.bonus_date
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setBonusDate(String bonusDate) {
        this.bonusDate = bonusDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gd_team_bonus.create_time
     *
     * @return the value of gd_team_bonus.create_time
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gd_team_bonus.create_time
     *
     * @param createTime the value for gd_team_bonus.create_time
     *
     * @mbg.generated Tue Nov 10 22:15:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}