package com.contract.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MAccountHitstory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.member_id
     *
     * @mbggenerated
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.currency
     *
     * @mbggenerated
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.total_balance
     *
     * @mbggenerated
     */
    private BigDecimal totalBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.frozen_balance
     *
     * @mbggenerated
     */
    private BigDecimal frozenBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.record_date
     *
     * @mbggenerated
     */
    private String recordDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_account_hitstory.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.id
     *
     * @return the value of m_account_hitstory.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.id
     *
     * @param id the value for m_account_hitstory.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.member_id
     *
     * @return the value of m_account_hitstory.member_id
     *
     * @mbggenerated
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.member_id
     *
     * @param memberId the value for m_account_hitstory.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.currency
     *
     * @return the value of m_account_hitstory.currency
     *
     * @mbggenerated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.currency
     *
     * @param currency the value for m_account_hitstory.currency
     *
     * @mbggenerated
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.total_balance
     *
     * @return the value of m_account_hitstory.total_balance
     *
     * @mbggenerated
     */
    public BigDecimal getTotalBalance() {
        return totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.total_balance
     *
     * @param totalBalance the value for m_account_hitstory.total_balance
     *
     * @mbggenerated
     */
    public void setTotalBalance(BigDecimal totalBalance) {
        this.totalBalance = totalBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.frozen_balance
     *
     * @return the value of m_account_hitstory.frozen_balance
     *
     * @mbggenerated
     */
    public BigDecimal getFrozenBalance() {
        return frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.frozen_balance
     *
     * @param frozenBalance the value for m_account_hitstory.frozen_balance
     *
     * @mbggenerated
     */
    public void setFrozenBalance(BigDecimal frozenBalance) {
        this.frozenBalance = frozenBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.record_date
     *
     * @return the value of m_account_hitstory.record_date
     *
     * @mbggenerated
     */
    public String getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.record_date
     *
     * @param recordDate the value for m_account_hitstory.record_date
     *
     * @mbggenerated
     */
    public void setRecordDate(String recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_account_hitstory.create_date
     *
     * @return the value of m_account_hitstory.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_account_hitstory.create_date
     *
     * @param createDate the value for m_account_hitstory.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}