package com.contract.entity;

import java.util.Date;

public class MailLogs {
    /**  */
    private Integer id;

    /** 发送方 */
    private String email;

    /** 参数 */
    private String params;

    /** 1验证码 2推广邮件 */
    private Integer type;

    /**  */
    private String content;

    /** 0未使用 1已使用 2已过期 */
    private Integer status;

    /**  */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.id
     *
     * @return the value of mail_logs.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.id
     *
     * @param id the value for mail_logs.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.email
     *
     * @return the value of mail_logs.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.email
     *
     * @param email the value for mail_logs.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.params
     *
     * @return the value of mail_logs.params
     *
     * @mbggenerated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.params
     *
     * @param params the value for mail_logs.params
     *
     * @mbggenerated
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.type
     *
     * @return the value of mail_logs.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.type
     *
     * @param type the value for mail_logs.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.content
     *
     * @return the value of mail_logs.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.content
     *
     * @param content the value for mail_logs.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.status
     *
     * @return the value of mail_logs.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.status
     *
     * @param status the value for mail_logs.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mail_logs.createtime
     *
     * @return the value of mail_logs.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mail_logs.createtime
     *
     * @param createtime the value for mail_logs.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}