package com.contract.entity;

import java.util.Date;

public class MtCliqueUser {
    /**  */
    private Integer id;

    /** 登录 */
    private String login;

    /** 目标id */
    private Integer targetid;

    /** 1总平台 2国家区域  3地区分公司 4国家 */
    private Integer type;

    /** 密码 */
    private String password;

    /** 名称 */
    private String name;

    /** 联系电话 */
    private String phone;

    /** 创建时间 */
    private Date createtime;

    /**  */
    private Integer roleid;

    /** 头像 */
    private String headurl;

    /** 0有效 -1无效 */
    private Integer status;
    
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.id
     *
     * @return the value of mt_clique_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.id
     *
     * @param id the value for mt_clique_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.login
     *
     * @return the value of mt_clique_user.login
     *
     * @mbggenerated
     */
    public String getLogin() {
        return login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.login
     *
     * @param login the value for mt_clique_user.login
     *
     * @mbggenerated
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.targetid
     *
     * @return the value of mt_clique_user.targetid
     *
     * @mbggenerated
     */
    public Integer getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.targetid
     *
     * @param targetid the value for mt_clique_user.targetid
     *
     * @mbggenerated
     */
    public void setTargetid(Integer targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.type
     *
     * @return the value of mt_clique_user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.type
     *
     * @param type the value for mt_clique_user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.password
     *
     * @return the value of mt_clique_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.password
     *
     * @param password the value for mt_clique_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.name
     *
     * @return the value of mt_clique_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.name
     *
     * @param name the value for mt_clique_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.phone
     *
     * @return the value of mt_clique_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.phone
     *
     * @param phone the value for mt_clique_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.createtime
     *
     * @return the value of mt_clique_user.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.createtime
     *
     * @param createtime the value for mt_clique_user.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.roleid
     *
     * @return the value of mt_clique_user.roleid
     *
     * @mbggenerated
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.roleid
     *
     * @param roleid the value for mt_clique_user.roleid
     *
     * @mbggenerated
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.headurl
     *
     * @return the value of mt_clique_user.headurl
     *
     * @mbggenerated
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.headurl
     *
     * @param headurl the value for mt_clique_user.headurl
     *
     * @mbggenerated
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_user.status
     *
     * @return the value of mt_clique_user.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_user.status
     *
     * @param status the value for mt_clique_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

	public String getRolename() {
		return rolename;
	}

	public void setRolename(String rolename) {
		this.rolename = rolename;
	}
    
    
}