package com.contract.entity;

import java.util.Date;
import java.util.List;

public class MtCliqueRoles {
    /**  */
    private Integer id;

    /** 角色名称 */
    private String name;

    /** 0有效 -1无效 */
    private Short status;

    /** 创建时间 */
    private Date createtime;

    /** 1总平台 2国家区域  3地区分公司 4国家 */
    private Integer type;

    /** 目标id */
    private Integer targetid;

    /** 角色菜单权限逗号分隔字符串 */
    private String menuids;
    
    private List<String> userList;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.id
     *
     * @return the value of mt_clique_roles.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.id
     *
     * @param id the value for mt_clique_roles.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.name
     *
     * @return the value of mt_clique_roles.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.name
     *
     * @param name the value for mt_clique_roles.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.status
     *
     * @return the value of mt_clique_roles.status
     *
     * @mbggenerated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.status
     *
     * @param status the value for mt_clique_roles.status
     *
     * @mbggenerated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.createtime
     *
     * @return the value of mt_clique_roles.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.createtime
     *
     * @param createtime the value for mt_clique_roles.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.type
     *
     * @return the value of mt_clique_roles.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.type
     *
     * @param type the value for mt_clique_roles.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.targetid
     *
     * @return the value of mt_clique_roles.targetid
     *
     * @mbggenerated
     */
    public Integer getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.targetid
     *
     * @param targetid the value for mt_clique_roles.targetid
     *
     * @mbggenerated
     */
    public void setTargetid(Integer targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mt_clique_roles.menuids
     *
     * @return the value of mt_clique_roles.menuids
     *
     * @mbggenerated
     */
    public String getMenuids() {
        return menuids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mt_clique_roles.menuids
     *
     * @param menuids the value for mt_clique_roles.menuids
     *
     * @mbggenerated
     */
    public void setMenuids(String menuids) {
        this.menuids = menuids;
    }

	public List<String> getUserList() {
		return userList;
	}

	public void setUserList(List<String> userList) {
		this.userList = userList;
	}

    
    
}