package com.contract.entity;

public class SysBanner {
    /**  */
    private Integer id;

    /** 图片 */
    private String imgurl;

    /** 新闻id */
    private Integer noticeid;

    /** 1.banner  2中层 */
    private Integer position;
    
    private String title;
    
    /**
     * 1APP 2PC
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_banner.id
     *
     * @return the value of sys_banner.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_banner.id
     *
     * @param id the value for sys_banner.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_banner.imgurl
     *
     * @return the value of sys_banner.imgurl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_banner.imgurl
     *
     * @param imgurl the value for sys_banner.imgurl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_banner.noticeid
     *
     * @return the value of sys_banner.noticeid
     *
     * @mbggenerated
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_banner.noticeid
     *
     * @param noticeid the value for sys_banner.noticeid
     *
     * @mbggenerated
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_banner.position
     *
     * @return the value of sys_banner.position
     *
     * @mbggenerated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_banner.position
     *
     * @param position the value for sys_banner.position
     *
     * @mbggenerated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
    
    
}