package com.contract.entity;

import java.util.Date;

import com.contract.common.DateUtil;
import com.contract.service.Page;

public class SysNotice extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = -7399752515906671878L;

	/**  */
    private Integer id;

    /**  */
    private String title;

    /**  */
    private String descval;

    /** 封面 */
    private String imgurl;

    /**  */
    private Date createtime;

    /** 1主页显示公告 ，2关于我们 */
    private Integer type;

    /**  */
    private String content;
    
    private String timestr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.id
     *
     * @return the value of sys_notice.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.id
     *
     * @param id the value for sys_notice.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.title
     *
     * @return the value of sys_notice.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.title
     *
     * @param title the value for sys_notice.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.descval
     *
     * @return the value of sys_notice.descval
     *
     * @mbggenerated
     */
    public String getDescval() {
        return descval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.descval
     *
     * @param descval the value for sys_notice.descval
     *
     * @mbggenerated
     */
    public void setDescval(String descval) {
        this.descval = descval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.imgurl
     *
     * @return the value of sys_notice.imgurl
     *
     * @mbggenerated
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.imgurl
     *
     * @param imgurl the value for sys_notice.imgurl
     *
     * @mbggenerated
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.createtime
     *
     * @return the value of sys_notice.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.createtime
     *
     * @param createtime the value for sys_notice.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.type
     *
     * @return the value of sys_notice.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.type
     *
     * @param type the value for sys_notice.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_notice.content
     *
     * @return the value of sys_notice.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_notice.content
     *
     * @param content the value for sys_notice.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }
    
    public String getTimestr() {
		if(createtime!=null) {
			timestr=DateUtil.toDateString(createtime, "yyyy-MM-dd HH:mm:ss");
		}
		return timestr;
	}
}