package com.contract.entity;

import java.util.Date;

import com.contract.service.Page;

public class TxLogs extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = 6170325174225046130L;

	/**  */
    private String hash;
    
    private Integer cid;

    /**  */
    private String blocknumber;

    /**  */
    private String timestamp;

    /**  */
    private String nonce;

    /**  */
    private String blockhash;

    /**  */
    private String fromaddr;

    /**  */
    private String contractaddress;

    /**  */
    private String toaddr;

    /**  */
    private String valuecoin;

    /**  */
    private String tokenname;

    /**  */
    private String tokensymbol;

    /**  */
    private String tokendecimal;

    /**  */
    private String gaslimit;

    /**  */
    private String gasprice;

    /**  */
    private String gasused;

    /**  */
    private Integer status;

    /**  */
    private String tarhash;

    /**  */
    private Date createtime;
    
    private Integer userid;
    
    private Integer salesman;
    
    private String salemanname;
    
    private String username;
    
    private Integer parentid;
    
    private String parentphone;
    
    private String parentname;
    
    private String login;
    
    private String realname;
    public TxLogs() {
    	
    }
    
    public TxLogs(String hash,Integer cid,String blocknumber,String timestamp,String nonce,String blockhash,String fromaddr,
    		String contractaddress,String toaddr,String valuecoin,
    		String tokenname,String tokensymbol,String tokendecimal,String gaslimit,String gasprice,String gasused) {
    		this.hash=hash;
    		this.cid=cid;
    		this.blocknumber=blocknumber;
    		this.timestamp=timestamp;
    		this.nonce=nonce;
    		this.blockhash=blockhash;
    		this.fromaddr=fromaddr;
    		this.contractaddress=contractaddress;
    		this.toaddr=toaddr;
    		this.valuecoin=valuecoin;
    		this.tokenname=tokenname;
    		this.tokensymbol=tokensymbol;
    		this.tokendecimal=tokendecimal;
    		this.gaslimit=gaslimit;
    		this.gasprice=gasprice;
    		this.gasused=gasused;
    		
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.hash
     *
     * @return the value of tx_logs.hash
     *
     * @mbggenerated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.hash
     *
     * @param hash the value for tx_logs.hash
     *
     * @mbggenerated
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.blocknumber
     *
     * @return the value of tx_logs.blocknumber
     *
     * @mbggenerated
     */
    public String getBlocknumber() {
        return blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.blocknumber
     *
     * @param blocknumber the value for tx_logs.blocknumber
     *
     * @mbggenerated
     */
    public void setBlocknumber(String blocknumber) {
        this.blocknumber = blocknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.timestamp
     *
     * @return the value of tx_logs.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.timestamp
     *
     * @param timestamp the value for tx_logs.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.nonce
     *
     * @return the value of tx_logs.nonce
     *
     * @mbggenerated
     */
    public String getNonce() {
        return nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.nonce
     *
     * @param nonce the value for tx_logs.nonce
     *
     * @mbggenerated
     */
    public void setNonce(String nonce) {
        this.nonce = nonce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.blockhash
     *
     * @return the value of tx_logs.blockhash
     *
     * @mbggenerated
     */
    public String getBlockhash() {
        return blockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.blockhash
     *
     * @param blockhash the value for tx_logs.blockhash
     *
     * @mbggenerated
     */
    public void setBlockhash(String blockhash) {
        this.blockhash = blockhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.fromaddr
     *
     * @return the value of tx_logs.fromaddr
     *
     * @mbggenerated
     */
    public String getFromaddr() {
        return fromaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.fromaddr
     *
     * @param fromaddr the value for tx_logs.fromaddr
     *
     * @mbggenerated
     */
    public void setFromaddr(String fromaddr) {
        this.fromaddr = fromaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.contractaddress
     *
     * @return the value of tx_logs.contractaddress
     *
     * @mbggenerated
     */
    public String getContractaddress() {
        return contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.contractaddress
     *
     * @param contractaddress the value for tx_logs.contractaddress
     *
     * @mbggenerated
     */
    public void setContractaddress(String contractaddress) {
        this.contractaddress = contractaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.toaddr
     *
     * @return the value of tx_logs.toaddr
     *
     * @mbggenerated
     */
    public String getToaddr() {
        return toaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.toaddr
     *
     * @param toaddr the value for tx_logs.toaddr
     *
     * @mbggenerated
     */
    public void setToaddr(String toaddr) {
        this.toaddr = toaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.valuecoin
     *
     * @return the value of tx_logs.valuecoin
     *
     * @mbggenerated
     */
    public String getValuecoin() {
        return valuecoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.valuecoin
     *
     * @param valuecoin the value for tx_logs.valuecoin
     *
     * @mbggenerated
     */
    public void setValuecoin(String valuecoin) {
        this.valuecoin = valuecoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.tokenname
     *
     * @return the value of tx_logs.tokenname
     *
     * @mbggenerated
     */
    public String getTokenname() {
        return tokenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.tokenname
     *
     * @param tokenname the value for tx_logs.tokenname
     *
     * @mbggenerated
     */
    public void setTokenname(String tokenname) {
        this.tokenname = tokenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.tokensymbol
     *
     * @return the value of tx_logs.tokensymbol
     *
     * @mbggenerated
     */
    public String getTokensymbol() {
        return tokensymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.tokensymbol
     *
     * @param tokensymbol the value for tx_logs.tokensymbol
     *
     * @mbggenerated
     */
    public void setTokensymbol(String tokensymbol) {
        this.tokensymbol = tokensymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.tokendecimal
     *
     * @return the value of tx_logs.tokendecimal
     *
     * @mbggenerated
     */
    public String getTokendecimal() {
        return tokendecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.tokendecimal
     *
     * @param tokendecimal the value for tx_logs.tokendecimal
     *
     * @mbggenerated
     */
    public void setTokendecimal(String tokendecimal) {
        this.tokendecimal = tokendecimal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.gaslimit
     *
     * @return the value of tx_logs.gaslimit
     *
     * @mbggenerated
     */
    public String getGaslimit() {
        return gaslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.gaslimit
     *
     * @param gaslimit the value for tx_logs.gaslimit
     *
     * @mbggenerated
     */
    public void setGaslimit(String gaslimit) {
        this.gaslimit = gaslimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.gasprice
     *
     * @return the value of tx_logs.gasprice
     *
     * @mbggenerated
     */
    public String getGasprice() {
        return gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.gasprice
     *
     * @param gasprice the value for tx_logs.gasprice
     *
     * @mbggenerated
     */
    public void setGasprice(String gasprice) {
        this.gasprice = gasprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.gasused
     *
     * @return the value of tx_logs.gasused
     *
     * @mbggenerated
     */
    public String getGasused() {
        return gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.gasused
     *
     * @param gasused the value for tx_logs.gasused
     *
     * @mbggenerated
     */
    public void setGasused(String gasused) {
        this.gasused = gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.status
     *
     * @return the value of tx_logs.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.status
     *
     * @param status the value for tx_logs.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.tarhash
     *
     * @return the value of tx_logs.tarhash
     *
     * @mbggenerated
     */
    public String getTarhash() {
        return tarhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.tarhash
     *
     * @param tarhash the value for tx_logs.tarhash
     *
     * @mbggenerated
     */
    public void setTarhash(String tarhash) {
        this.tarhash = tarhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_logs.createtime
     *
     * @return the value of tx_logs.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_logs.createtime
     *
     * @param createtime the value for tx_logs.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getSalesman() {
		return salesman;
	}

	public void setSalesman(Integer salesman) {
		this.salesman = salesman;
	}

	public String getSalemanname() {
		return salemanname;
	}

	public void setSalemanname(String salemanname) {
		this.salemanname = salemanname;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getParentphone() {
		return parentphone;
	}

	public void setParentphone(String parentphone) {
		this.parentphone = parentphone;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Integer getCid() {
		return cid;
	}

	public void setCid(Integer cid) {
		this.cid = cid;
	}
    
    
}