package com.contract.entity;

import java.util.Date;

import com.contract.service.Page;

public class UsdtRechargeLog extends Page{
    /**
	 * 
	 */
	private static final long serialVersionUID = -3337206931079577097L;

	/**  */
    private Integer id;

    /**  */
    private Integer cid;

    /** hash单号 */
    private String hash;

    /** 时间戳 */
    private String timestamp;

    /** 交易发起方地址 */
    private String fromaddr;

    /** 交易收款方地址 */
    private String toaddr;

    /**  */
    private String valuecoin;

    /**  */
    private String gasused;

    /** -1未处理 0已处理 */
    private Integer status;

    /** 处理转入到总平台单号 */
    private String tarhash;

    /**  */
    private Date createtime;
    
    private String login;
    
    private Integer userid;
    
    private String username;
    
    private String realname;
    
    private Integer parentid;
    
    private String parentphone;
    
    private String parentname;
    
    private Integer salesman;
    
    private String salemanname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.id
     *
     * @return the value of usdt_recharge_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.id
     *
     * @param id the value for usdt_recharge_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.cid
     *
     * @return the value of usdt_recharge_log.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.cid
     *
     * @param cid the value for usdt_recharge_log.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.hash
     *
     * @return the value of usdt_recharge_log.hash
     *
     * @mbggenerated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.hash
     *
     * @param hash the value for usdt_recharge_log.hash
     *
     * @mbggenerated
     */
    public void setHash(String hash) {
        this.hash = hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.timestamp
     *
     * @return the value of usdt_recharge_log.timestamp
     *
     * @mbggenerated
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.timestamp
     *
     * @param timestamp the value for usdt_recharge_log.timestamp
     *
     * @mbggenerated
     */
    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.fromaddr
     *
     * @return the value of usdt_recharge_log.fromaddr
     *
     * @mbggenerated
     */
    public String getFromaddr() {
        return fromaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.fromaddr
     *
     * @param fromaddr the value for usdt_recharge_log.fromaddr
     *
     * @mbggenerated
     */
    public void setFromaddr(String fromaddr) {
        this.fromaddr = fromaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.toaddr
     *
     * @return the value of usdt_recharge_log.toaddr
     *
     * @mbggenerated
     */
    public String getToaddr() {
        return toaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.toaddr
     *
     * @param toaddr the value for usdt_recharge_log.toaddr
     *
     * @mbggenerated
     */
    public void setToaddr(String toaddr) {
        this.toaddr = toaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.valuecoin
     *
     * @return the value of usdt_recharge_log.valuecoin
     *
     * @mbggenerated
     */
    public String getValuecoin() {
        return valuecoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.valuecoin
     *
     * @param valuecoin the value for usdt_recharge_log.valuecoin
     *
     * @mbggenerated
     */
    public void setValuecoin(String valuecoin) {
        this.valuecoin = valuecoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.gasused
     *
     * @return the value of usdt_recharge_log.gasused
     *
     * @mbggenerated
     */
    public String getGasused() {
        return gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.gasused
     *
     * @param gasused the value for usdt_recharge_log.gasused
     *
     * @mbggenerated
     */
    public void setGasused(String gasused) {
        this.gasused = gasused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.status
     *
     * @return the value of usdt_recharge_log.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.status
     *
     * @param status the value for usdt_recharge_log.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.tarhash
     *
     * @return the value of usdt_recharge_log.tarhash
     *
     * @mbggenerated
     */
    public String getTarhash() {
        return tarhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.tarhash
     *
     * @param tarhash the value for usdt_recharge_log.tarhash
     *
     * @mbggenerated
     */
    public void setTarhash(String tarhash) {
        this.tarhash = tarhash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usdt_recharge_log.createtime
     *
     * @return the value of usdt_recharge_log.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usdt_recharge_log.createtime
     *
     * @param createtime the value for usdt_recharge_log.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public Integer getUserid() {
		return userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Integer getParentid() {
		return parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getParentphone() {
		return parentphone;
	}

	public void setParentphone(String parentphone) {
		this.parentphone = parentphone;
	}

	public String getParentname() {
		return parentname;
	}

	public void setParentname(String parentname) {
		this.parentname = parentname;
	}

	public Integer getSalesman() {
		return salesman;
	}

	public void setSalesman(Integer salesman) {
		this.salesman = salesman;
	}

	public String getSalemanname() {
		return salemanname;
	}

	public void setSalemanname(String salemanname) {
		this.salemanname = salemanname;
	}
	
	
    
}