package com.contract.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsdtRechargeLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public UsdtRechargeLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andHashIsNull() {
            addCriterion("hash is null");
            return (Criteria) this;
        }

        public Criteria andHashIsNotNull() {
            addCriterion("hash is not null");
            return (Criteria) this;
        }

        public Criteria andHashEqualTo(String value) {
            addCriterion("hash =", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotEqualTo(String value) {
            addCriterion("hash <>", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashGreaterThan(String value) {
            addCriterion("hash >", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashGreaterThanOrEqualTo(String value) {
            addCriterion("hash >=", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashLessThan(String value) {
            addCriterion("hash <", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashLessThanOrEqualTo(String value) {
            addCriterion("hash <=", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashLike(String value) {
            addCriterion("hash like", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotLike(String value) {
            addCriterion("hash not like", value, "hash");
            return (Criteria) this;
        }

        public Criteria andHashIn(List<String> values) {
            addCriterion("hash in", values, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotIn(List<String> values) {
            addCriterion("hash not in", values, "hash");
            return (Criteria) this;
        }

        public Criteria andHashBetween(String value1, String value2) {
            addCriterion("hash between", value1, value2, "hash");
            return (Criteria) this;
        }

        public Criteria andHashNotBetween(String value1, String value2) {
            addCriterion("hash not between", value1, value2, "hash");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNull() {
            addCriterion("timestamp is null");
            return (Criteria) this;
        }

        public Criteria andTimestampIsNotNull() {
            addCriterion("timestamp is not null");
            return (Criteria) this;
        }

        public Criteria andTimestampEqualTo(String value) {
            addCriterion("timestamp =", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotEqualTo(String value) {
            addCriterion("timestamp <>", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThan(String value) {
            addCriterion("timestamp >", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampGreaterThanOrEqualTo(String value) {
            addCriterion("timestamp >=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThan(String value) {
            addCriterion("timestamp <", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLessThanOrEqualTo(String value) {
            addCriterion("timestamp <=", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampLike(String value) {
            addCriterion("timestamp like", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotLike(String value) {
            addCriterion("timestamp not like", value, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampIn(List<String> values) {
            addCriterion("timestamp in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotIn(List<String> values) {
            addCriterion("timestamp not in", values, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampBetween(String value1, String value2) {
            addCriterion("timestamp between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andTimestampNotBetween(String value1, String value2) {
            addCriterion("timestamp not between", value1, value2, "timestamp");
            return (Criteria) this;
        }

        public Criteria andFromaddrIsNull() {
            addCriterion("fromaddr is null");
            return (Criteria) this;
        }

        public Criteria andFromaddrIsNotNull() {
            addCriterion("fromaddr is not null");
            return (Criteria) this;
        }

        public Criteria andFromaddrEqualTo(String value) {
            addCriterion("fromaddr =", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrNotEqualTo(String value) {
            addCriterion("fromaddr <>", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrGreaterThan(String value) {
            addCriterion("fromaddr >", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrGreaterThanOrEqualTo(String value) {
            addCriterion("fromaddr >=", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrLessThan(String value) {
            addCriterion("fromaddr <", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrLessThanOrEqualTo(String value) {
            addCriterion("fromaddr <=", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrLike(String value) {
            addCriterion("fromaddr like", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrNotLike(String value) {
            addCriterion("fromaddr not like", value, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrIn(List<String> values) {
            addCriterion("fromaddr in", values, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrNotIn(List<String> values) {
            addCriterion("fromaddr not in", values, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrBetween(String value1, String value2) {
            addCriterion("fromaddr between", value1, value2, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andFromaddrNotBetween(String value1, String value2) {
            addCriterion("fromaddr not between", value1, value2, "fromaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrIsNull() {
            addCriterion("toaddr is null");
            return (Criteria) this;
        }

        public Criteria andToaddrIsNotNull() {
            addCriterion("toaddr is not null");
            return (Criteria) this;
        }

        public Criteria andToaddrEqualTo(String value) {
            addCriterion("toaddr =", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrNotEqualTo(String value) {
            addCriterion("toaddr <>", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrGreaterThan(String value) {
            addCriterion("toaddr >", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrGreaterThanOrEqualTo(String value) {
            addCriterion("toaddr >=", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrLessThan(String value) {
            addCriterion("toaddr <", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrLessThanOrEqualTo(String value) {
            addCriterion("toaddr <=", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrLike(String value) {
            addCriterion("toaddr like", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrNotLike(String value) {
            addCriterion("toaddr not like", value, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrIn(List<String> values) {
            addCriterion("toaddr in", values, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrNotIn(List<String> values) {
            addCriterion("toaddr not in", values, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrBetween(String value1, String value2) {
            addCriterion("toaddr between", value1, value2, "toaddr");
            return (Criteria) this;
        }

        public Criteria andToaddrNotBetween(String value1, String value2) {
            addCriterion("toaddr not between", value1, value2, "toaddr");
            return (Criteria) this;
        }

        public Criteria andValuecoinIsNull() {
            addCriterion("valuecoin is null");
            return (Criteria) this;
        }

        public Criteria andValuecoinIsNotNull() {
            addCriterion("valuecoin is not null");
            return (Criteria) this;
        }

        public Criteria andValuecoinEqualTo(String value) {
            addCriterion("valuecoin =", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinNotEqualTo(String value) {
            addCriterion("valuecoin <>", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinGreaterThan(String value) {
            addCriterion("valuecoin >", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinGreaterThanOrEqualTo(String value) {
            addCriterion("valuecoin >=", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinLessThan(String value) {
            addCriterion("valuecoin <", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinLessThanOrEqualTo(String value) {
            addCriterion("valuecoin <=", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinLike(String value) {
            addCriterion("valuecoin like", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinNotLike(String value) {
            addCriterion("valuecoin not like", value, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinIn(List<String> values) {
            addCriterion("valuecoin in", values, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinNotIn(List<String> values) {
            addCriterion("valuecoin not in", values, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinBetween(String value1, String value2) {
            addCriterion("valuecoin between", value1, value2, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andValuecoinNotBetween(String value1, String value2) {
            addCriterion("valuecoin not between", value1, value2, "valuecoin");
            return (Criteria) this;
        }

        public Criteria andGasusedIsNull() {
            addCriterion("gasused is null");
            return (Criteria) this;
        }

        public Criteria andGasusedIsNotNull() {
            addCriterion("gasused is not null");
            return (Criteria) this;
        }

        public Criteria andGasusedEqualTo(String value) {
            addCriterion("gasused =", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedNotEqualTo(String value) {
            addCriterion("gasused <>", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedGreaterThan(String value) {
            addCriterion("gasused >", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedGreaterThanOrEqualTo(String value) {
            addCriterion("gasused >=", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedLessThan(String value) {
            addCriterion("gasused <", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedLessThanOrEqualTo(String value) {
            addCriterion("gasused <=", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedLike(String value) {
            addCriterion("gasused like", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedNotLike(String value) {
            addCriterion("gasused not like", value, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedIn(List<String> values) {
            addCriterion("gasused in", values, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedNotIn(List<String> values) {
            addCriterion("gasused not in", values, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedBetween(String value1, String value2) {
            addCriterion("gasused between", value1, value2, "gasused");
            return (Criteria) this;
        }

        public Criteria andGasusedNotBetween(String value1, String value2) {
            addCriterion("gasused not between", value1, value2, "gasused");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTarhashIsNull() {
            addCriterion("tarhash is null");
            return (Criteria) this;
        }

        public Criteria andTarhashIsNotNull() {
            addCriterion("tarhash is not null");
            return (Criteria) this;
        }

        public Criteria andTarhashEqualTo(String value) {
            addCriterion("tarhash =", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashNotEqualTo(String value) {
            addCriterion("tarhash <>", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashGreaterThan(String value) {
            addCriterion("tarhash >", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashGreaterThanOrEqualTo(String value) {
            addCriterion("tarhash >=", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashLessThan(String value) {
            addCriterion("tarhash <", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashLessThanOrEqualTo(String value) {
            addCriterion("tarhash <=", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashLike(String value) {
            addCriterion("tarhash like", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashNotLike(String value) {
            addCriterion("tarhash not like", value, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashIn(List<String> values) {
            addCriterion("tarhash in", values, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashNotIn(List<String> values) {
            addCriterion("tarhash not in", values, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashBetween(String value1, String value2) {
            addCriterion("tarhash between", value1, value2, "tarhash");
            return (Criteria) this;
        }

        public Criteria andTarhashNotBetween(String value1, String value2) {
            addCriterion("tarhash not between", value1, value2, "tarhash");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usdt_recharge_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}