package com.contract.dto;

import java.math.BigDecimal;
import java.util.Date;

import com.contract.common.DateUtil;
import com.contract.enums.HandleTypeEnums;
import com.contract.service.Page;

public class MoneyDto extends Page{


    /**
	 * 
	 */
	private static final long serialVersionUID = 7816301849789366434L;

	/**  */
    private Integer id;

    /** 流水号 */
    private String paycode;

    /** 会员编号 */
    private Integer cid;

    /** 操作类型见枚举类 */
    private Integer typeid;

    /** 1收入 0支出 */
    private Integer isout;

    /** 上一次值 */
    private BigDecimal original;

    /** 本次操作值 */
    private BigDecimal cost;

    /** 最后值 */
    private BigDecimal last;

    /** 创建时间 */
    private Date createtime;

    /** 修改时间 用来做乐观锁 */
    private Date updatetime;

    /** 目标用户id */
    private Integer targetid;

    /** 备注 */
    private String remark;
    
    private String timestr;
    
    private String type;
    
    private String typename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.id
     *
     * @return the value of c_usdt_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.id
     *
     * @param id the value for c_usdt_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.paycode
     *
     * @return the value of c_usdt_detail.paycode
     *
     * @mbggenerated
     */
    public String getPaycode() {
        return paycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.paycode
     *
     * @param paycode the value for c_usdt_detail.paycode
     *
     * @mbggenerated
     */
    public void setPaycode(String paycode) {
        this.paycode = paycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.cid
     *
     * @return the value of c_usdt_detail.cid
     *
     * @mbggenerated
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.cid
     *
     * @param cid the value for c_usdt_detail.cid
     *
     * @mbggenerated
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.typeid
     *
     * @return the value of c_usdt_detail.typeid
     *
     * @mbggenerated
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.typeid
     *
     * @param typeid the value for c_usdt_detail.typeid
     *
     * @mbggenerated
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.isout
     *
     * @return the value of c_usdt_detail.isout
     *
     * @mbggenerated
     */
    public Integer getIsout() {
        return isout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.isout
     *
     * @param isout the value for c_usdt_detail.isout
     *
     * @mbggenerated
     */
    public void setIsout(Integer isout) {
        this.isout = isout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.original
     *
     * @return the value of c_usdt_detail.original
     *
     * @mbggenerated
     */
    public BigDecimal getOriginal() {
        return original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.original
     *
     * @param original the value for c_usdt_detail.original
     *
     * @mbggenerated
     */
    public void setOriginal(BigDecimal original) {
        this.original = original;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.cost
     *
     * @return the value of c_usdt_detail.cost
     *
     * @mbggenerated
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.cost
     *
     * @param cost the value for c_usdt_detail.cost
     *
     * @mbggenerated
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.last
     *
     * @return the value of c_usdt_detail.last
     *
     * @mbggenerated
     */
    public BigDecimal getLast() {
        return last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.last
     *
     * @param last the value for c_usdt_detail.last
     *
     * @mbggenerated
     */
    public void setLast(BigDecimal last) {
        this.last = last;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.createtime
     *
     * @return the value of c_usdt_detail.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.createtime
     *
     * @param createtime the value for c_usdt_detail.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.updatetime
     *
     * @return the value of c_usdt_detail.updatetime
     *
     * @mbggenerated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.updatetime
     *
     * @param updatetime the value for c_usdt_detail.updatetime
     *
     * @mbggenerated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.targetid
     *
     * @return the value of c_usdt_detail.targetid
     *
     * @mbggenerated
     */
    public Integer getTargetid() {
        return targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.targetid
     *
     * @param targetid the value for c_usdt_detail.targetid
     *
     * @mbggenerated
     */
    public void setTargetid(Integer targetid) {
        this.targetid = targetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column c_usdt_detail.remark
     *
     * @return the value of c_usdt_detail.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column c_usdt_detail.remark
     *
     * @param remark the value for c_usdt_detail.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        if (typeid != null && typeid > 100) {
            this.remark = HandleTypeEnums.getNameCn(remark);
            return;
        }
        this.remark = remark;
    }

	public String getTimestr() {
		if(createtime!=null) {
			timestr=DateUtil.toDateString(createtime, "yyyy-MM-dd HH:mm:ss");
		}
		return timestr;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

    public String getTypename() {
        if (typeid != null) {
            if (typeid > 100) {
                typename= HandleTypeEnums.transfer.getName();
            } else {
                typename = HandleTypeEnums.getName(typeid);
            }
        }
        return typename;
    }

    

}
