package com.contract.dao;

import com.contract.dto.MoneyDto;
import com.contract.dto.SalesTeamDto;
import com.contract.dto.TeamVo;
import com.contract.entity.CContractOrder;
import com.contract.entity.CCustomer;
import com.contract.entity.CCustomerExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int countByExample(CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int deleteByExample(CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int insert(CCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int insertSelective(CCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    List<CCustomer> selectByExampleWithBLOBs(CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    List<CCustomer> selectByExample(CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    CCustomer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CCustomer record, @Param("example") CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") CCustomer record, @Param("example") CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CCustomer record, @Param("example") CCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated 
     */
    int updateByPrimaryKeyWithBLOBs(CCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_customer
     *
     * @mbggenerated
     */ 
    int updateByPrimaryKey(CCustomer record);

	CCustomer getByInvitationcode(String parentcode);

	CCustomer getByPhone(String phone);

	List<CCustomer> queryList(CCustomer customer);

	BigDecimal getTotalmoney(CCustomer customer);

	List<Map<String, Object>> queryUnder(CCustomer cus);

	List<TeamVo> queryTeam(Integer id);

	Integer selectAuthGrade(Integer id);

    /**
     * 获取业务员团队总信息
     * String salesman
     * @return
     */
	List<SalesTeamDto> getSalesTeam(CCustomer cus);

    /**
     * 获取u用户总转入转出
     * Integer cid
     * @param cid
     * @return
     */
    List<MoneyDto> getUserTransfer(SalesTeamDto s);
}