package com.contract.dao;

import com.contract.dto.MoneyDto;
import com.contract.entity.CZcDetail;
import com.contract.entity.CZcDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CZcDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int countByExample(CZcDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int deleteByExample(CZcDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int insert(CZcDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int insertSelective(CZcDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    List<CZcDetail> selectByExample(CZcDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    CZcDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CZcDetail record, @Param("example") CZcDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CZcDetail record, @Param("example") CZcDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CZcDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CZcDetail record);

	List<MoneyDto> queryZcDetail(MoneyDto detail);
}