package com.contract.dao;

import com.contract.dto.ReportDto;
import com.contract.entity.CZcOrder;
import com.contract.entity.CZcOrderExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CZcOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int countByExample(CZcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int deleteByExample(CZcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int insert(CZcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int insertSelective(CZcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    List<CZcOrder> selectByExample(CZcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    CZcOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CZcOrder record, @Param("example") CZcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CZcOrder record, @Param("example") CZcOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CZcOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_zc_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CZcOrder record);

	CZcOrder getByOrdercode(String ordercode);

	List<CZcOrder> queryZCList(CZcOrder zcOrder);

	ReportDto getZcMoney(CZcOrder zcOrder);
}