import axios from 'axios'

import {
    Message
} from 'element-ui'
import {
    getLang
} from './utils'

var message_arr = [
    'OCR_FRONT_ERROR',
    'OCR_BACK_ERROR',
    'OCR_IDCARD_ALREADY',
    'OCR_REQUEST_TO_OFTEN',
    'UNDER_REVIEW',
    'AUDIT_SUCCEEDED',
    'LANG_NO_LOGIN',
    'LANG_ID_NUM_ALREADY_EXIST',
    'Please upload the front and back of ID card before face comparison',
    'PORTRAIT_CONTRAST_ERROR',
    'OCR_UPLOAD_FRONT_IMAGE_EXCEED_SIZE',
    'OCR_UPLOAD_BACK_IMAGE_EXCEED_SIZE',
    'PORTRAIT_CONTRAST_UPLOAD_IMAGE_EXCEED_SIZE',
    "UNDEFINE_ERROR",
    "PARAMS_ERROR",
    "LANG_NO_LOGIN",
    "LANG_SMSCODE_ERR_TIP",
    "LANG_SMSCODE_NULL_TIP",
    "LANG_SEC_PWD_TIP",
    "LANG_GOOGLE_CODE_NULL",
    "LANG_GOOGLE_CODE_ERROR",
    "LANG_AUTH_IDENTITY_FIRST",
    "LANG_MAIL_NULL_TIP",
    "LANG_PWD_NULL_TIP",
    "LANG_ALREADY_REG_FINDPWD",
    "LANG_ACCOUNT_LOCKED",
    "LANG_PLEASE_LOGIN_AFTER_REGISTRATION",
    "LANG_OLD_PWD_ERR_TIP",
    "LANG_PWD_SAME_TIP",
    "LANG_ILLEGAL_FROM",
    "LANG_M_NAME_ERROR_TIP",
    "LANG_ILLEGAL_CHECK_CODE",
    "LANG_ILLEGAL_GT_CHECK_CODE",
    "LANG_ACCOUNT_NOT_EXIST",
    "LANG_MAIL_FAIL",
    "LANG_OLD_GOOGLE_CODE_ERROR",
    "LANG_UNDEFINED_ERROR",
    "LANG_ALI_OSS_ERROR",
    "LANG_ID_NUM_ALREADY_EXIST",
    "LANG_AUTH_IDENTITY_SUB_SUCCESS",
    "LANG_ILLEGAL_ID",
    "LANG_API_TOKEN_NOT_EXIST",
    "LANG_API_LABEL_ERR",
    "LANG_API_PRIVILEGE_ERR",
    "LANG_INVALID_NAME",
    "LANG_ILLEGAL_CURRENCY",
    "LANG_CANNOT_WITHDRAW",
    "LANG_ILLEGAL_ADDRESS",
    "LANG_WITHDRAW_ADDR_NULL_TIP",
    "LANG_WITHDRAW_LABEL_NULL_TIP",
    "LANG_ILLEGAL_AMOUNT",
    "LANG_WITHDRAW_AMOUNT_MIN_THAN_MIN_TIP",
    "LANG_STOP_EX",
    "LANG_ILLEGAL_WITHDRAW_ID",
    "LANG_ILLEGAL_WITHDRAW_STATUS",
    "LANG_REPEAT_ADDRESS",
    "LANG_ILLEGAL_STATUS",
    "LANG_ILLEGAL_REJECT_REASON",
    "LANG_ILLEGAL_TRADE_PAIR",
    "LANG_ORDER_DOES_NOT_EXIST",
    "LANG_MARKET_ORDER_CANNOT_BE_CANCELLED",
    "LANG_ORDER_IS_DONE_OR_CANCELED",
    "LANG_ILLEGAL_SYMBOL",
    "LANG_ILLEGAL_ORDER_ID",
    "LANG_ILLEGAL_PRICE",
    "LANG_ILLEGAL_O_PRICE_TYPE",
    "LANG_ILLEGAL_O_TYPE",
    "LANG_ILLEGAL_SOURCE",
    "LANG_SYMBOL_NOT_OPEN_TRADE_RANK",
    "LANG_SYMBOL_OPEN_TRADE_RANK",
    "LANG_ILLEGAL_ADS_TYPE",
    "LANG_SYMBOL_NOT_TRADE_RANK_DATA",
    "LANG_TRADE_RANK_NOT_END_NOT_REWORD",
    "LANG_REWORD_HAS_SEND",
    "PASSWORD_ERROR",
    "LANG_INVALID_EMAIL_OR_PASSWORD",
    "API_ACCESS_COUNT_MAX",
    "LANG_API_COUNT_MAX_3",
    "API_NOT_EXISTS",
    "LANG_ILLEGAL_IP",
    "API_NO_PRIVILEGE",
    "LANG_LITTLE_THAN_MIN_BUYVOLUME_TIP",
    "LANG_LITTLE_THAN_MIN_BUYAMOUNT_TIP",
    "LANG_LITTLE_THAN_MIN_SELLVOLUME_TIP",
    "NOT_SUFFICIENT_FUNDS",
    "LANG_ERROR_A_TYPE",
    "LANG_ORDER_NOT_EXISTS",
    "LANG_ORDER_ALREADY_CONFIRMED",
    "LANG_ILLEGAL_ADS_ID",
    "LANG_ILLEGAL_ACCOUNT_TYPE",
    "LANG_WAITING_ORDER_CONFIRM_MAX_THAN_2",
    "LANG_WAITING_ORDER_MAX_THAN_2",
    "LANG_ACCOUNT_HAS_PROBLEM",
    "LANG_POOL_NO_ADDRESS_EXISTS",
    "LANG_ADDRESS_ALREADY_EXISTS",
    "LANG_WITHDRAW_STATUS_IS_NOT_WATTING",
    "LANG_CREATE_ORDER_FAIL",
    "LANG_ACCOUNT_FUNDS_PROBLEM",
    "LANG_CANCEL_ORDER_ERROR",
    "LANG_ORDER_TRADE_ERROR",
    "LANG_FIND_CONDITION_NOT_NULL",
    "PASSWORD_ERROR",
    "PLEASE_SELECT_CURRENCY",
    "TRADE_AREA_HAS_NUMBER_ONE_SYMBOL",
    "BASE_CURRENCY_NOT_EXISTS",
    "QUOTE_CURRENCY_NOT_EXISTS",
    "ACCESS_HAS_BEEN_DENIED",
    "DEL_COLUMN_TIP",
    "SEND_AUDIT_ARTICLE_TIP",
    "AUDIT_ARTICLE_TIP",
    "BASE_AND_QUOTE_CURRENCY_NOT_CONSISTENT",
    "ORDER_STATUS_NOT_CONFIRM",
    "ADS_HAS_USED_NOT_DELETE",
    "ACCOUNT_HAS_LOCKED",
    "ACCOUNT_OR_PASSWORD_ERROR",
    "LOGIN_INFO_ERROR",
    "PLEASE_SELECT_SYMBOL",
    'TOKEN_NOT_EXISTS',
    "LANG_LIMIT_FREQUENCY_OPERTION",
    "LANG_SMSCODE_EXPIRE_TIP",
    "LANG_LOGIN_TOKEN_EXPIRE",
    "LANG_DATA_TOO_LONG",
    "LANG_DATA_TOO_BIG",
    "LANG_DATA_ERROR",
    "LANG_REQ_METHOD_NOT_EXIST",
    "LANG_CAST_TYPE_EXCEPTION",
    "LANG_REQ_PARAM_ERROR",
    "LANG_LIMIT_OPERTION",
    'LANG_USER_NOT_EXIST',
    'LANG_INVALID_BINDNAME',
    'FLASH_SALE_NOT_START',
    'LANG_BIGGER_THAN_MAX_BUYVOLUME_TIP',
    'CURRENCY_WITHDRAWAL_EXCEPTION',
    'WITHDRAW_ADDR_ILLEGAL',
    'LANG_EXIST_ORDER',
    'ERROR_CURRENCY',
    'LANG_BIGGER_THAN_MAX_PRICE',
    'LANG_BIGGER_THAN_MIN_PRICE',
    'LANG_INVALID_PRICE_UPS_DOWN_HIGH',
    'LANG_INVALID_PRICE_UPS_DOWN_LOW',
    'CONTRACT_INVITATION_CODE_DOES_NOT_EXIST',
    'CONTRACT_INVITATION_CODE_DOES_NOT_NULL',
    'CONTRACT_INVITATION_CODE_ALREADY_EXISTS',
    'INSUFFICIENT_RESIDUAL_ASSETS',
    'LANG_OPERTION_FAIL',
    'LACK_OF_EFFECTIVE_ASSETS',
    'LANG_SYSTEM_BUSY',
    'CONTRACT_VA_OPERATION_LIMIT',
    'CONTRACT_ANALOG_ACCOUNT_NO_INVITER'
];
var message_arr_zh = [
    '身份证正面识别失败',
    '身份证背面识别失败',
    '该身份证已被实名',
    '因请求过于频繁，您已被系统限制，请您在24小时后再次进行实名',
    '您的实名认证正在审核中，请耐心等待哦',
    '您的实名认证已经审核成功请勿重复提交',
    '请先登录',
    '证件号已经存在',
    '请您先上传身份证正反面再进行人脸比对',
    '人像对比失败',
    '您上传的身份证正面超出上传大小，请压缩后重试',
    '您上传的身份证背面超出上传大小，请压缩后重试',
    '您上传的图片超出上传大小，请压缩后重试',
    "未知错误",
    "参数错误",
    "请先登录",
    "验证码错误",
    "验证码必填",
    "资金密码错误",
    "谷歌验证码为空",
    "谷歌验证码错误",
    "请先完成实名认证",
    "请输入邮箱",
    "请输入密码",
    "该账号已注册",
    "该账号已锁定",
    "该账号未完成注册",
    "原密码错误",
    "安全密码和登录密码不能一致",
    "请求来源非法",
    "账号格式错误",
    "图片验证码错误",
    "按钮证码错误",
    "无此币种资产",
    "发送验证码失败",
    "原谷歌验证码错误",
    "原谷歌验证码错误",
    "获取上传信息失败",
    "证件号已经存在",
    "身份认证申请提交成功",
    "错误的ID",
    "ApiToken不存在",
    "Api标签不能为空",
    "Api权限不能为空",
    "请输入用户名",
    "不存在的币种",
    "暂停提现",
    "不存在的地址",
    "提现地址必填",
    "提现标签必填",
    "错误的数量",
    "提现金额小于最低提现额",
    "暂停交易",
    "错误的提现ID",
    "提现状态不为待处理，不能取消",
    "重复添加地址",
    "错误的提现状态",
    "拒绝提现",
    "错误的交易对",
    "订单不存在",
    "市价单不允许取消",
    "订单已成交或已经取消",
    "错误的交易对",
    "错误的订单ID",
    "错误的价格",
    "错误的价格类型",
    "错误的订单类型",
    "错误的订单来源",
    "该交易对没有开启交易排名",
    "该交易对已开启交易排名",
    "广告类型错误",
    "该交易对没有交易排名数据",
    "交易排名没有结束不能发送奖励!",
    "该交易排名奖励已发放不能重复发送!",
    "对不起您输入的当前密码有误！",
    "账号或密码错误",
    "api访问过于频繁",
    "api数量不能超过3个",
    "api不存在",
    "ip地址不合法",
    "api没有权限",
    "数量小于最小买入数量",
    "总额小于最小买入总额",
    "数量小于最小卖出数量",
    "账户资金不足",
    "错误的账户类型(只支持 银行卡 支付宝 微信)",
    "订单不存在",
    "订单不是待付款状态",
    "广告ID不存在",
    "请完善对应的收款设置",
    "超过两个订单待处理，不能再添加新订单",
    "超过两个订单未付款，不能再添加新订单",
    "该用户账户可疑，冻结余额大于总金额",
    "该币种地址不存在",
    "该币种地址已存在",
    "提现正在处理中",
    "创建订单失败",
    "账户资金错误",
    "取消订单异常",
    "订单交易异常",
    "查询条件不能为空",
    "对不起，您输入的当前密码有误！",
    "请选择币种！",
    "该交易区已有排名第一的交易!",
    "基础货币不存在!",
    "基础货币不存在!",
    "您没有访问此页面的权限！",
    "本栏目已经使用，不能删除，您可以修改它的是否启用为“否”！",
    "只有状态为新建的文章才可以送审，修改文章可以使文章状态变成新建！",
    "只有状态为待审核的文章才可以审核！",
    "基础货币和计价货币不能一致 ！",
    "该订单状态不为未确认 ！",
    "本广告主已经使用，不能删除！",
    "对不起，您的账号已被锁定,请与管理员联系！",
    "您输入的用户名或密码错误！",
    "用户登录信息错误！",
    "请选择交易对！",
    "登录出错，请重新登录",
    "短信操作过于频繁，请稍后再试！",
    "验证码已失效! ",
    "页面失效，请重新登录！",
    "数据太长！",
    "数据太大！",
    "数据异常！",
    "请求的方法不存在！",
    "类型转换错误！",
    "请求参数类型不正确！",
    "已经达到操作限制，不能进行操作",
    "用户不存在！",
    "绑定名字与实名认证名字不一致",
    "未开放此抢购",
    "数量大于最大购买量",
    '提币失败',
    '提币地址不合法',
    '您有未完成的全仓订单',
    '该币种无划转权限',
    '下单价大于最大限定价',
    '下单价小于最小限定价',
    '超过当日最大涨幅限价',
    '低于当日最大跌幅限价',
    '邀请码不存在',
    '邀请码不能为空',
    '邀请码已存在',
    '提现后剩余总资产要大于等于5 USDT',
    '操作失败',
    '有效资产不足',
    '系统繁忙',
    '模拟账号没有此操作权限',
    '模拟账号不能作为邀请'
];
var message_arr_en = [
    'unknown mistake',
    'Parameter error',
    'please log in first',
    'Verification code error',
    'Verification code required',
    'Capital password error',
    'Google verification code is empty',
    'Google verification code error',
    'Please complete the real name certification first.',
    'please input your email',
    'Please enter your password',
    'This account is already registered',
    'The account is locked',
    'The account has not been registered',
    'The original password is wrong',
    'The security password and login password cannot be the same.',
    'Illegal request source',
    'Account format error',
    'Image verification code error',
    'Button certificate error',
    'Account does not exist',
    'Send verification code failed',
    'Original Google verification code error',
    'Original Google verification code error',
    'Failed to get upload information',
    'The document number already exists',
    'Successfully submitted the identity application',
    'Wrong ID',
    'ApiToken does not exist',
    'Api tag cannot be empty',
    'Api permission cannot be empty',
    'please enter user name',
    'Non-existent currency',
    'Suspension withdrawal',
    'Address that does not exist',
    'Cash withdrawal address is required',
    'Cash withdrawal label is required',
    'Number of errors',
    'The amount of cash raised is less than the minimum withdrawal amount',
    'Suspend trading',
    'Wrong withdrawal ID',
    'The withdrawal status is not pending and cannot be cancelled.',
    'Repeat adding addresses',
    'Wrong withdrawal status',
    'Refuse to withdraw cash',
    'Wrong transaction pair',
    'Order does not exist',
    'Market order is not allowed to cancel',
    'Order has been cancelled or cancelled',
    'Wrong transaction pair',
    'Bad order ID',
    'Wrong price',
    'Wrong price type',
    'Wrong order type',
    'Wrong order source',
    'The transaction does not open the transaction ranking',
    'The transaction ranks the opened trades',
    'Ad type error',
    'The transaction has no transaction ranking data',
    'The transaction ranking is not over and the reward cannot be sent.',
    'The transaction ranking award has been issued and cannot be sent repeatedly',
    'Sorry, the current password you entered is incorrect!',
    'Incorrect username or password',
    'Api access is too frequent',
    'The number of apis cannot exceed 3',
    'Api does not exist',
    'Ip address is illegal',
    'Api does not have permission',
    'The quantity is less than the minimum purchase quantity',
    'Total is less than the minimum purchase amount',
    'The quantity is less than the minimum sold quantity',
    'Insufficient account funds',
    'Wrong account type (only support bank card Alipay WeChat)',
    'Order does not exist',
    'Order is not pending status',
    'Ad ID does not exist',
    'Please improve the corresponding payment settings',
    'More than two orders are pending, no new orders can be added',
    'More than two orders have not been paid, no new orders can be added',
    'The user account is suspicious and the frozen balance is greater than the total amount',
    'The currency address does not exist',
    'The currency address already exists',
    'Withdrawal is in progress',
    'Create order failed',
    'Account funding error',
    'Cancel order exception',
    'Order transaction is abnormal',
    'The query condition cannot be empty',
    'Sorry, the current password you entered is incorrect!',
    'Please choose a currency!',
    'The trading zone has the number one trade',
    'Base currency does not exist',
    'Base currency does not exist',
    'You do not have permission to access this page!',
    'This section is already in use and cannot be deleted. You can modify whether it is enabled as "No"!',
    'Only articles with a new status can be submitted for review. Modifying an article can make the status of the article new!',
    'Only articles with a status of pending review can be reviewed!',
    'The base currency and the denomination currency are not consistent',
    'The order status is not unconfirmed',
    'This advertiser has been used and cannot be deleted!',
    'Sorry, your account has been locked.',
    'The username or password you entered is incorrect!',
    'User login information is wrong!',
    'Please choose the deal pair!',
    'Login error, please log in again',
    'SMS operation is too frequent, please try again later!',
    'Verification code has expired',
    'The page is invalid, please log in again',
    'The data is too long!',
    'The data is too big!',
    'The data is abnormal!',
    'The requested method does not exist!',
    'Type conversion error!',
    'Request parameter type is incorrect!',
    'The operating limit has been reached and cannot be operated',
    "This snap up is not open",
    "Mention money failed",
    "Mention money failed",
    'The address is illegal',
    'The remaining total assets after withdrawal should be greater than or equal to 5 usdt',
    'operation failed',
    'Effective with insufficient assets',
    'System busy',
    'The simulated account does not have this operation permission',
    'Simulation account cannot be used as an invitation'
];
var message_arr_ja = [
    "不明なエラー",
    "パラメータエラー",
    "最初にログインしてください",
    "確認コードエラー",
    "確認コードが必要です",
    "大文字パスワードエラー",
    "Googleの確認コードが空です",
    "Google確認コードエラー",
    "最初に本名認証を完了してください。",
    "あなたのメールアドレスを入力してください",
    "パスワードを入力してください",
    "このアカウントは既に登録されています",
    "アカウントはロックされています",
    "アカウントは登録されていません",
    "元のパスワードが間違っている",
    "セキュリティパスワードとログインパスワードを同じにすることはできません。",
    "不正な要求元",
    "アカウントフォーマットエラー",
    "画像確認コードエラー",
    "ボタン証明書エラー",
    "そのような通貨資産はありません",
    "確認コードの送信に失敗しました",
    "元のGoogle確認コードエラー",
    "元のGoogle確認コードエラー",
    "アップロード情報を取得できませんでした",
    "伝票番号はすでに存在します",
    "IDアプリケーションを正常に送信しました",
    "間違ったID",
    "ApiTokenは存在しません",
    "Apiタグは空にできません",
    "Api許可は空にできません",
    "ユーザー名を入力してください",
    "存在しない通貨",
    "一時停止撤回",
    "存在しない住所",
    "現金引き出しアドレスが必要です",
    "現金引き出しラベルが必要です",
    "エラー数",
    "集められた現金の額が最低出金額より少ない",
    "取引を中断する",
    "間違った引き出しID",
    "撤退ステータスは保留中ではなく、キャンセルすることはできません。",
    "アドレスの追加を繰り返す",
    "間違った引き出しステータス",
    "現金を引き出すことを拒否",
    "間違ったトランザクションペア",
    "注文が存在しません",
    "成行注文はキャンセルできません",
    "注文がキャンセルされたかキャンセルされました",
    "間違ったトランザクションペア",
    "間違った注文ID",
    "間違った価格",
    "間違った価格タイプ",
    "間違った注文タイプ",
    "間違った注文元",
    "トランザクションはトランザクションのランキングを開きません",
    "取引はオープン取引をランク付けします",
    "広告タイプエラー",
    "トランザクションにトランザクションのランク付けデータがありません",
    "取引のランキングが終わっていないと報酬を送信することはできません!",
    "トランザクションランキングアワードが発行されており、繰り返し送信することはできません!",
    "申し訳ありませんが、現在入力したパスワードは間違っています",
    "アカウントまたはパスワードが正しくありません",
    "APIアクセスが多すぎる",
    "apisの数は3を超えてはいけません",
    "Apiは存在しません",
    "IPアドレスが不正です",
    "Apiには許可がありません",
    "数量が最小購入数量より少ない",
    "合計が最小購入金額を下回っています",
    "数量が最小販売数量より少ない",
    "口座資金が足りない",
    "間違った口座タイプ（サポート銀行カードAlipay WeChatのみ）",
    "注文が存在しません",
    "注文は保留状態ではありません",
    "広告IDが存在しません",
    "対応する支払い設定を改善してください",
    "3つ以上の注文が保留中です。新しい注文を追加することはできません",
    "2つ以上の注文が支払われていません、新しい注文を追加することはできません",
    "ユーザーアカウントが不審で、凍結残高が合計金額を超えています",
    "通貨アドレスが存在しません",
    "通貨アドレスは既に存在します",
    "出金は処理中です",
    "注文の作成に失敗しました",
    "アカウント資金エラー",
    "注文例外のキャンセル",
    "注文取引が異常です",
    "クエリ条件は空にできません",
    "申し訳ありませんが、現在入力したパスワードは間違っています。",
    "通貨を選択してください",
    "取引ゾーンはすでにナンバーワンの取引をしています!",
    "基本通貨が存在しません!",
    "基本通貨が存在しません!",
    "このページにアクセスする権限がありません。",
    "このセクションは既に使用されているため削除できません。「いいえ」として有効になっているかどうかを変更できます。",
    "新しいステータスの記事のみをレビューのために送信できます記事を変更すると、その記事のステータスが新しいものになります。",
    "レビュー待ちのステータスの記事のみをレビューできます。",
    "基本通貨と額面通貨が一致していません ！",
    "注文状況が未確認ではない ！",
    "この広告主は使用されているため削除できません。",
    "アカウントがロックされています。管理者に連絡してください",
    "入力したユーザー名またはパスワードが正しくありません。",
    "ユーザーログイン情報が間違っています。",
    "ディールペアを選択してください！",
    "ログインエラーです。もう一度ログインしてください",
    "SMS操作が多すぎます。しばらくしてからもう一度お試しください。",
    "確認コードが期限切れです! ",
    "ページが無効です。もう一度ログインしてください。",
    "データが長すぎます。",
    "データが大きすぎます。",
    "データが異常です。",
    "要求されたメソッドは存在しません。",
    "型変換エラーです。",
    "リクエストパラメータタイプが正しくありません。",
    "操作限界に達したため操作できません",
    "ユーザーが存在しません。",
    "バインディング名が実名認証名と矛盾しています。",
    "この買占めは開放されていない",
    "数量は最大購入量より多い",
    "挙幣に失敗する",
    "挙幣に失敗する",
    '引き出しのアドレスは合法ではない',
    '現金引き出し後の残存総資産は5 US DT以上であること。',
    '操作に失敗しました',
    '効果が不十分な資産',
    'システムが忙しい',
    'デモ口座のないこの許可',
    'アナログアカウントは招待として使えません。'
];
var message_arr_ko = [
    "알 수없는 오류",
    "매개 변수 오류",
    "먼저 로그인하십시오.",
    "인증 코드 오류",
    "인증 코드 필요",
    "대문자 암호 오류",
    "Google 인증 코드가 비어 있습니다.",
    "Google 인증 코드 오류",
    "실명 인증을 먼저 작성하십시오.",
    "이메일 주소를 입력하십시오.",
    "비밀번호를 입력하십시오.",
    "이 계정은 이미 등록되어 있습니다.",
    "계정이 잠겼습니다.",
    "계정이 등록되지 않았습니다.",
    "원래 비밀번호가 잘못되었습니다.",
    "보안 암호와 로그인 암호는 같을 수 없습니다.",
    "불법적 인 요청 출처",
    "계정 형식 오류",
    "이미지 인증 코드 오류",
    "버튼 인증서 오류",
    "그러한 통화 자산 없음",
    "인증 코드 전송 실패",
    "원래의 Google 인증 코드 오류",
    "원래의 Google 인증 코드 오류",
    "업로드 정보를 가져 오지 못했습니다.",
    "문서 번호가 이미 있습니다.",
    "ID 응용 프로그램을 성공적으로 제출했습니다.",
    "잘못된 ID",
    "ApiToken은 존재하지 않습니다",
    "Api 태그는 비워 둘 수 없습니다",
    "API 사용 권한은 비워 둘 수 없습니다",
    "사용자 이름을 입력하십시오",
    "존재하지 않는 통화",
    "서스펜션 인출",
    "존재하지 않는 주소",
    "현금 인출 주소가 필요합니다",
    "현금 인출 라벨이 필요합니다",
    "오류 수",
    "제기 된 현금 금액이 최소 인출 금액보다 적습니다",
    "일시 중지 거래",
    "잘못된 철수 ID",
    "출금 상태는 보류 중이 아니며 취소 할 수 없습니다",
    "주소 추가 반복",
    "잘못된 철수 상태",
    "현금 인출 거부",
    "잘못된 거래 쌍",
    "주문이 없습니다",
    "시장 주문은 취소 할 수 없습니다",
    "주문이 취소 또는 취소되었습니다",
    "잘못된 거래 쌍",
    "잘못된 주문 ID",
    "잘못된 가격",
    "가격 유형이 잘못되었습니다",
    "잘못된 주문 유형",
    "잘못된 주문 출처",
    "트랜잭션이 트랜잭션 순위를 열지 않습니다",
    "거래는 열린 거래의 순위를 매 깁니다",
    "광고 유형 오류",
    "거래에는 거래 순위 데이터가 없습니다",
    "거래 순위가 끝나지 않아 보상을 보낼 수 없습니다!",
    "거래 등급 보너스가 발행되었으며 반복적으로 보낼 수 없습니다!",
    "죄송합니다. 입력하신 현재 비밀번호가 잘못되었습니다.",
    "잘못된 계정 또는 비밀번호",
    "API 액세스가 너무 빈번 함",
    "API 수는 3을 초과 할 수 없습니다.",
    "API 는 존재하지 않습니다.",
    "IP 주소가 잘못되었습니다.",
    "API 에 권한이 없습니다.",
    "수량이 최소 구매 수량보다 적습니다.",
    "총 구매액이 최소 구매 금액보다 적습니다.",
    "수량이 최소 판매 수량보다 적습니다.",
    "불충분 한 계정 자금",
    "잘못된 계좌 유형 (은행 카드 Alipay WeChat 만 지원)",
    "주문이 없습니다.",
    "주문이 보류 중 상태가 아닙니다.",
    "광고 ID가 없습니다.",
    "해당 지급 설정을 개선하십시오.",
    "두 개 이상의 주문이 보류 중입니다. 새 주문을 추가 할 수 없습니다.",
    "2 개 이상의 주문이 지불되지 않았으므로 새로운 주문을 추가 할 수 없습니다.",
    "사용자 계정이 의심스럽고 고정 된 잔액이 총 금액보다 큽니다.",
    "통화 주소가 존재하지 않습니다.",
    "통화 주소가 이미 있습니다.",
    "탈퇴가 처리 중입니다.",
    "주문 생성 실패",
    "계정 자금 오류",
    "주문 예외 취소",
    "주문 거래가 비정상입니다.",
    "쿼리 조건은 비워 둘 수 없습니다.",
    "죄송합니다. 입력하신 현재 비밀번호가 잘못되었습니다.",
    "통화를 선택하십시오!",
    "거래 지역은 이미 거래가 1 위입니다!",
    "기본 통화가 존재하지 않습니다!",
    "기본 통화가 존재하지 않습니다!",
    "이 페이지에 액세스 할 수있는 권한이 없습니다.",
    "이 섹션은 이미 사용 중이며 삭제할 수 없습니다. 사용 설정 여부를  아니요 로 수정할 수 있습니다!",
    "새로운 상태의 기사 만 검토를 위해 제출할 수 있습니다. 기사를 수정하면 기사의 상태가 새롭게 바뀔 수 있습니다!",
    "검토 대기중인 상태의 기사 만 검토 할 수 있습니다!",
    "기본 통화와 명칭 통화가 일치하지 않습니다 ！",
    "주문 상태가 확인되지 않았습니다 ！",
    "이 광고주는 사용되어 삭제할 수 없습니다.",
    "죄송합니다. 계정이 잠겼습니다. 관리자에게 문의하십시오!",
    "입력 한 사용자 이름 또는 암호가 틀립니다!",
    "사용자 로그인 정보가 잘못되었습니다!",
    "거래 쌍을 선택하십시오!",
    "로그인 오류입니다. 다시 로그인하십시오.",
    "SMS 작업이 너무 빈 번한 경우 나중에 다시 시도하십시오!",
    "인증 코드가 만료되었습니다! ",
    "페이지가 잘못되었습니다. 다시 로그인하십시오!",
    "데이터가 너무 깁니다!",
    "데이터가 너무 큽니다!",
    "데이터가 비정상입니다!",
    "요청한 메소드가 존재하지 않습니다!",
    "유형 변환 오류!",
    "요청 매개 변수 유형이 잘못되었습니다.",
    "작동 한계에 도달하여 작동 할 수 없음",
    "사용자가 존재하지 않습니다!",
    "바인딩 이름이 실제 이름 인증 이름과 일치하지 않습니다.",
    "아직 앞다투어 구입하는 것을 개방하지 않았다",
    "수량이 최대 구매량보다 많다.",
    "화폐 인출 실패",
    "화폐 인출 실패",
    '인출 주소가 비합법적이다',
    '현금 을 인출 한 후 남 은 총 자산 은 5 USDT 보다 크 거나 같 아야 한다.',
    '조작 실패',
    '유효 자산 이 부족 하 다',
    '시스템 이 바쁘다',
    '아 날로 그 계 정 은 이 조작 권한 이 없습니다.',
    '아 날로 그 계 정 은 초대 할 수 없습니다.'
];

var service = axios.create({
})

service.interceptors.request.use(
    config => {
        let token = localStorage.getItem('chatRoom_Token')
        if (token === null) {
            token = 'web';
        }
        config.headers = {
            'token': token
        }
        return config
    },
)

service.interceptors.response.use(
    response => {
        let lang = getLang()
        if (!lang) {
            lang = 'zh'
        }
        if (response.data) {
            const res = response.data
            if (res.success === 1) {
                return res
            }
            if (res.state === 1) {
                return response.data
            } else if (res.state === -1) {
                if (res.msg === 'SYMBOL_FEE_ACCOUNT_NOT_AUTH') {
                    return res
                }

                if (res.msg === 'LANG_NO_LOGIN') {
                    return res
                }
                let index = message_arr.indexOf(res.msg)

                if (lang == 'zh') {
                    Message({
                        message: message_arr_zh[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                } else if (lang == 'en') {
                    Message({
                        message: message_arr_en[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                } else if (lang == 'ko') {
                    Message({
                        message: message_arr_ko[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                } else if (lang == 'ja') {
                    Message({
                        message: message_arr_ja[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                }

                return res
            } else if (res.state > 500000) {
                if (res.msg === 'LANG_NO_LOGIN') {
                    return res
                }
                let index = message_arr.indexOf(res.msg)

                if (lang == 'zh') {
                    Message({
                        message: message_arr_zh[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                } else if (lang == 'en') {
                    Message({
                        message: message_arr_en[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                } else if (lang == 'ko') {
                    Message({
                        message: message_arr_ko[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                } else if (lang == 'ja') {
                    Message({
                        message: message_arr_ja[index],
                        type: 'error',
                        duration: 3000,
                        showClose: true
                    })
                }

                return res
            } else {
                return res
            }
        } else {
            return response.data
        }

    },
    error => {
        // for debug
        // Message({
        //   message: error.message,
        //   type: 'error',
        //   duration: 5 * 1000
        // })
        return Promise.reject(error)
    }
)


export default service
