package com.pmzhongguo.ex.business.mapper;

import com.contract.dto.ReportDto;
import com.contract.entity.CContractOrder;
import com.contract.entity.CContractOrderExample;
import com.pmzhongguo.ex.core.mapper.SuperMapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;

public interface CContractOrderMapper extends SuperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int countByExample(CContractOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int deleteByExample(CContractOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int insert(CContractOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int insertSelective(CContractOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    List<CContractOrder> selectByExample(CContractOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    CContractOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CContractOrder record, @Param("example") CContractOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CContractOrder record, @Param("example") CContractOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CContractOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_contract_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CContractOrder record);

	List<CContractOrder> queryOrderList(CContractOrder order);

	CContractOrder getByOrdercode(String ordercode);

	BigDecimal getFrozen(Integer id);

	ReportDto getOrderMoney(CContractOrder order);

}