package com.pmzhongguo.ex.business.mapper;

import com.contract.entity.CWallet;
import com.contract.entity.CWalletExample;
import com.pmzhongguo.ex.business.dto.AccountHistoryDto;
import com.pmzhongguo.ex.core.mapper.SuperMapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ContractWalletMapper extends SuperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int countByExample(CWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int deleteByExample(CWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("cid") Integer cid, @Param("type") String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int insert(CWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int insertSelective(CWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    List<CWallet> selectByExample(CWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    CWallet selectByPrimaryKey(@Param("cid") Integer cid, @Param("type") String type);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CWallet record, @Param("example") CWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CWallet record, @Param("example") CWalletExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CWallet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_wallet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CWallet record);

    int updateMoneyLockVersion(CWallet wallet);

    CWallet getByAddr(String referenceaddress);

    CWallet getByCid(Integer cid);

    CWallet getByLabel(String label);

    public List<AccountHistoryDto> selectWalletPage(Map<String, Object> map);
}