package com.pmzhongguo.ex.business.mapper;

import com.contract.dto.MoneyDto;
import com.contract.entity.CUsdtDetail;
import com.contract.entity.CUsdtDetailExample;
import com.pmzhongguo.ex.core.mapper.SuperMapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

public interface CUsdtDetailMapper extends SuperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int countByExample(CUsdtDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int deleteByExample(CUsdtDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int insert(CUsdtDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int insertSelective(CUsdtDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    List<CUsdtDetail> selectByExample(CUsdtDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    CUsdtDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CUsdtDetail record, @Param("example") CUsdtDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CUsdtDetail record, @Param("example") CUsdtDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CUsdtDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table c_usdt_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CUsdtDetail record);

	List<MoneyDto> queryUsdtDetail(MoneyDto detail);

	BigDecimal getMoneyByTargetid(CUsdtDetail cUsdtDetail);

    List<MoneyDto> selectPage(Map<String, Object> params);
}