package com.pmzhongguo.ex.business.mapper;

import com.contract.entity.GdDetail;
import com.contract.entity.GdDetailExample;
import com.pmzhongguo.ex.core.mapper.SuperMapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GdDetailMapper extends SuperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    long countByExample(GdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int deleteByExample(GdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int insert(GdDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int insertSelective(GdDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    List<GdDetail> selectByExample(GdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    GdDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int updateByExampleSelective(@Param("record") GdDetail record, @Param("example") GdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int updateByExample(@Param("record") GdDetail record, @Param("example") GdDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int updateByPrimaryKeySelective(GdDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentary_detail
     *
     * @mbg.generated Tue Nov 10 16:17:49 CST 2020
     */
    int updateByPrimaryKey(GdDetail record);
}