package com.zytx.common.mapper;

import com.zytx.common.entity.MMember;
import com.zytx.common.entity.MMemberExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface MMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int countByExample(MMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int deleteByExample(MMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int insert(MMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int insertSelective(MMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    List<MMember> selectByExample(MMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    MMember selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MMember record, @Param("example") MMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MMember record, @Param("example") MMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_member
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MMember record);
}